### ISSUE TITLE
Error occur when using testrpc

### ISSUE THREAD

**Issue by rjl493456442** [ConsenSys-archive/ganache-cli-archive#100]
when i type in testrpc in terminal, i got this error message. How can i fix it?

```
testrpc
/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/eth-lightwallet/node_modules/tweetnacl/nacl-fast.js:2152
       throw new TypeError('unexpected type ' + t + ', use Uint8Array');
             ^
TypeError: unexpected type [object Object], use Uint8Array
    at checkArrayTypes (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/eth-lightwallet/node_modules/tweetnacl/nacl-fast.js:2152:14)
    at Object.nacl.secretbox (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/eth-lightwallet/node_modules/tweetnacl/nacl-fast.js:2201:3)
    at Function.KeyStore._encryptString (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/eth-lightwallet/lib/keystore.js:113:21)
    at new KeyStore (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/eth-lightwallet/lib/keystore.js:91:29)
    at new Blockchain (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/blockchain.js:48:19)
    at new Manager (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/manager.js:15:21)
    at Object.Server.provider (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/server.js:153:19)
    at Object.Server.server (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/server.js:23:25)
    at Object.TestRPC.server (/usr/local/lib/node_modules/ethereumjs-testrpc/index.js:23:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/ethereumjs-testrpc/bin/testrpc:43:22)
```

**Comment by tcoulter** [comment]
You'll need to upgrade to node 5 or higher.

**Comment by mathcrypto** [comment]
I would like to know where is the keystore and geth.ipc files of testrpc stored?
