### ISSUE TITLE
msbuild error when installing on windows.

### ISSUE THREAD

**Issue by ResourceHog** [ConsenSys-archive/ganache-cli-archive#101]
I get this weird error when trying to install
`npm install -g --python=python2.7 --msvs-version=2015 ethereumjs-testrpc`

```
C:\WINDOWS\system32>npm install -g --python=python2.7 --msvs-version=2015 ethereumjs-testrpc
C:\Users\dfg\AppData\Roaming\npm\testrpc -> C:\Users\dfg\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\bin\testrpc

> secp256k1@3.1.0 install C:\Users\dfg\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\secp256k1
> npm run rebuild


> secp256k1@3.1.0 rebuild C:\Users\dfg\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\secp256k1
> node-gyp rebuild


C:\Users\dfg\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Users\dfg\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140')
cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by sele
cting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [C:\Users\dfg\AppData\Roaming\npm\node_modules\ethereumjs-testrp
c\node_modules\secp256k1\build\secp256k1.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\dfg\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\dfg\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\dfg\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\secp256k1
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\dfg\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "rebuild"
npm ERR! node v4.4.5
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! secp256k1@3.1.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@3.1.0 rebuild script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs secp256k1
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\dfg\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\secp256k1\npm-debug.log
C:\Users\dfg\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\dfg\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "--python=python2.7" "--msvs-version=2015" "ethereumjs-testrpc"
npm ERR! node v4.4.5
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! secp256k1@3.1.0 install: `npm run rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@3.1.0 install script 'npm run rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs secp256k1
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log
npm ERR! code 1
```

**Comment by ResourceHog** [comment]
`npm install -g --python=python2.7 --msvs-version=2015 secp256k1`

gives me the exact same error which makes me think that it's related to secp256k1 specifically.

**Comment by jmdfm** [comment]
This would seem to be an issue with `secp256k1` on Windows. Usually this is because OpenSSL has not been installed correctly

Did you follow the instructions here? https://github.com/ethereumjs/testrpc/wiki/Installing-TestRPC-on-Windows

Failing that you should probably open an issue with the `secp256k1` team: https://github.com/cryptocoinjs/secp256k1-node/issues

**Comment by tcoulter** [comment]
From the error message, it looks as though this is your issue:

> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...".

Have you tried following the directions in the error message?

**Comment by tcoulter** [comment]
Closing this for housekeeping purposes. Let us know if you run into any issues, and don't hesitate to check out the ethereumjs gitter: https://gitter.im/ethereum/ethereumjs-lib
