### ISSUE TITLE
MS Build Error while installing

### ISSUE THREAD

**Issue by Abhijith68** [ConsenSys-archive/ganache-cli-archive#102]
![image](https://cloud.githubusercontent.com/assets/17248470/15884078/582a1196-2d6b-11e6-979d-a3011cfff045.png)

**Comment by ResourceHog** [comment]
i get the same error as well see #101 . What have you tried?

**Comment by Abhijith68** [comment]
I've tried but it didn't work
Pls suggest me how can I clone it.?

**Comment by tcoulter** [comment]
It looks like you're using Node 6.0. I haven't tried that. Can you give Node 5.x a try?

**Comment by jmdfm** [comment]
@Abhijith68 Can you confirm that you followed the installation instructions for Windows here https://github.com/ethereumjs/testrpc/wiki/Installing-TestRPC-on-Windows

**Comment by Abhijith68** [comment]
@johnmcdowall I've followed the same instrustions.

**Comment by istrau2** [comment]
+1

**Comment by brendan87** [comment]
+1

**Comment by oculushut** [comment]
Just wondering, but did anybody figure out what the problem was?  On Node 6 here too... may downgrade later today to give it another go...

**Comment by oculushut** [comment]
Failed on Node version 6.1.0 for me earlier.  Same problem with Node version 5.9.0:

```
E:\PROJECT>npm install -g ethereumjs-testrpc
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
npm WARN addRemoteGit     at emitTwo (events.js:100:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:185:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:850:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:323:11)
npm WARN addRemoteGit     at emitOne (events.js:90:13)
npm WARN addRemoteGit     at Socket.emit (events.js:182:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:479:12)
npm WARN addRemoteGit  debris/bignumber.js#94d7146671b9719e00a09c29b01a691bc85048c2 resetting remote C:\Users\USERNAME\AppData\Roaming\npm-cache\_git-remotes\git-github-com-debris-bignumber-js-git-94d714667
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
C:\Users\USERNAME\AppData\Roaming\npm\testrpc -> C:\Users\USERNAME\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\bin\testrpc

> secp256k1@3.1.0 install C:\Users\USERNAME\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\secp256k1
> npm run rebuild


> secp256k1@3.1.0 rebuild C:\Users\USERNAME\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\secp256k1
> node-gyp rebuild


C:\Users\USERNAME\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Users\USERNAME\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolse
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\USERNAME\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\secp256k1\build\secp256k1.


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "e:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\USERNAME\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\USERNAME\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\secp256k1
gyp ERR! node -v v5.9.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "e:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\USERNAME\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "rebuild"
npm ERR! node v5.9.0
npm ERR! npm  v3.8.2
npm ERR! code ELIFECYCLE
npm ERR! secp256k1@3.1.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@3.1.0 rebuild script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs secp256k1
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\USERNAME\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\secp256k1\npm-debug.log
C:\Users\USERNAME\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "e:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\USERNAME\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ethereumjs-testrpc"
npm ERR! node v5.9.0
npm ERR! npm  v3.8.2
npm ERR! code ELIFECYCLE

npm ERR! secp256k1@3.1.0 install: `npm run rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@3.1.0 install script 'npm run rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs secp256k1
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\PROJECT\npm-debug.log
npm ERR! code 1

E:\PROJECT>
```

**Comment by chansonm** [comment]
I have the same problem (see picture). i tried everything, installed all the stuff three times, of course I followed your installation instructions for Windows (exception: i dont understand point "4. Add the directory containing "solc.exe" to your path. The binary is available in the latest webthree-umbrella release."). Ok, the FAQ and you say its probably an error with installing OpenSSL, but honestly, what could I do wrong with installing that? Well, I downloaded it several times, installed it (32, 64), and yeah, I added all the variables to my system path....... any idea how to overcome the problem? I am really trying hard, but it just wont work out. and i dont seem to be the only one with that problem....

**Comment by chansonm** [comment]
![testrpcerror](https://cloud.githubusercontent.com/assets/19322211/16451405/1ede4e4a-3e03-11e6-8651-424f4d10cbf1.png)

**Comment by chansonm** [comment]
![sysvariables](https://cloud.githubusercontent.com/assets/19322211/16451469/94e17f36-3e03-11e6-8dbb-f769e621ffd5.png)

**Comment by chansonm** [comment]
I get basically the same error with node v4.4.7 installed

**Comment by chansonm** [comment]
any ideas @johnmcdowall ?

**Comment by tcoulter** [comment]
@chansonm From the pictures you've shown, it appears as though you've ran into multiple errors, and neither is the same one. For instance, the first screenshot you posted tells you to install the .NET framework or Visual Studio 2005 (the error message is about 8 lines down from the top). The next screenshot you posted is a different error, stating that a file was not found (this isn't a file I've ever heard of). Regarding this last error, it does seem problematic that MSBUILD is looking for a properties file at the root of the C:/ drive. 

I'm going to close this issue as there are too many items reported in it. Please open a new one with a screenshot that represents the most current error. You can reference this issue. In the new issue's title, reference the actual error reported by MSBUILD. And before posting this issue, make sure you google it first! This doesn't sound like an issue specific to the TestRPC, and rather a configuration issue getting Visual Studio to work correctly.
