### ISSUE TITLE
fail to specify multiple accounts

### ISSUE THREAD

**Issue by dyzz** [ConsenSys-archive/ganache-cli-archive#129]
`$ testrpc --account="<privatekey>,balance" [--account="<privatekey>,balance"]` end up only creating the first account.

```

➜ ~ testrpc --account ",1000" --account ",1000"
EthereumJS TestRPC v2.1.0

Available Accounts

(0) 0x3fdaa629e9e533020de02d1ebc0aa779012b3fb9

Private Keys

(0) 2b2a45921e854f0dc0888e78fd75063633ae5d4280e9edc8ccee8ee637ab2ea5

Listening on localhost:8545
```

Environment:
OSX 10.12,  node 4.4.5, ethereumjs-testrpc v2.1.0

**Comment by tcoulter** [comment]
As far as I can tell, this has been fixed: 

```
$ ./bin/testrpc --account="0x39d2655d02ad43240aab071883f94ec17241df16732d1424df965857dc15ea35,100000000" --account="0xd64c6e055dda4700c178a7153cb4ce75c7b74fd97ec5fd4643bb40e42e5576ed,1000000"
EthereumJS TestRPC v2.2.3

Available Accounts
==================
(0) 0xa4e384a0ce1601581dba668c0fb632f5a339f933
(1) 0x5669fafb524be112d278007b96ae77dbf1d12a0b

Private Keys
==================
(0) 39d2655d02ad43240aab071883f94ec17241df16732d1424df965857dc15ea35
(1) d64c6e055dda4700c178a7153cb4ce75c7b74fd97ec5fd4643bb40e42e5576ed

Listening on localhost:8545
```

Note that I'm running this locally from my checkout of the testrpc. 

Closing this ticket. Please file a new ticket if you run into more issues.

**Comment by dyzz** [comment]
Missing index for deriving new account if not provided secret key

```
➜  ~ testrpc --account=",100000000" --account=",1000000"

/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/solc/bin/soljson-latest.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS
AssertionError: Invalid index
    at /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/hdkey/lib/hdkey.js:86:5
    at Array.forEach (native)
    at HDKey.derive (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/hdkey/lib/hdkey.js:78:11)
    at EthereumHDKey.derivePath (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-wallet/hdkey.js:37:32)
    at StateManager.createAccount (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/statemanager.js:119:28)
    at Array.map (native)
    at StateManager.initialize (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/statemanager.js:64:33)
    at new GethApiDouble (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/subproviders/geth_api_double.js:21:14)
    at Object.Interface.provider (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/interface.js:160:25)
    at Object.Interface.server (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/interface.js:28:25)
```

**Comment by tcoulter** [comment]
You're not specifying the private key for the accounts you're trying to add. You need to pass in the private key so it can determine which accounts are available.

**Comment by dyzz** [comment]
This used to be working on <=Ver 2.0.7. It's handy if you just want to set specific balance. 

https://github.com/dyzz/testrpc/commit/cf75effe07f2a746733c4ec70f4062607d464a8f
