### ISSUE TITLE
Starting testrpc with blocktime option fails

### ISSUE THREAD

**Issue by elenadimitrova** [ConsenSys-archive/ganache-cli-archive#142]
Strting testrpc witha blocktime option of anything but 0 fails, for example
`testrpc -b 1` produces the following

```
EthereumJS TestRPC v2.2.0

Available Accounts
==================
(0) 0x177aefe0c6acbf3770dac7637c3eb5dcb62a8c24
(1) 0x244b7c2c4f8b17fe791a78ee653075f6a1c0c305
(2) 0x33a78c6eea49893c2bb92dba120bc871fc01ea17
(3) 0x96f70190104c70cee0cfb3b996f77de4aca1d8f7
(4) 0x2f9b020001b94c1c27dc540ab7f23a42a2eebe11
(5) 0x1b636ddb8a1a8d4b4021481a06bdc16f7224d979
(6) 0x4fdc933299e271d14028340b5b9e8897013e2c4f
(7) 0x70034826f3a57b47182fe357a0d4a8f554ab44a0
(8) 0xcec8449291613ebe8c68b3c07515ed7bfdf39dcb
(9) 0x7e03e70f0c3407e20e1c3d76a2a6f967ffd9a9f8

Private Keys
==================
(0) 14f7634cb224ad18f8bd1df262a5dfe0bb0395c377146c25bbb3801c53128199
(1) 8e0a918ae9f65a6f879d24e277ca132ff6b49acb4d32487893c3b018085d0538
(2) 05a37a9124ce8fea0b8c3788baf89d3a110aef37137d442105e9c28ced2a9d7c
(3) 232572d2c8b26f50718ad1a1fa64a671876f4e3bbccb844625f3bd9658593b89
(4) 4fd039f653a28fc6fef3f00cd99345a20deb9b7315a3fd489d16f323a0cff1e1
(5) 32c07cd1c64c26e485677f78cc85bd0f93d3e7069723e6b483d761419209e347
(6) ea5927513e1cfebd942c2102619026b1efc88209178e9eb9de51ec8b6fdf16ed
(7) bb75edd5d8f693a241c4d8852d041a29a15ab7fe39690b37c397c84254bb00e0
(8) 291f1be272de76855e6bd17b44d3a515ea001723b08e133349176bb0eebf0784
(9) b5639a811206bdde140b737adf38adfde1013c4f3d5817e9f018a702cdc6ebb5

HD Wallet
==================
Mnemonic:      nothing around electric prison east spot tell sauce horse sugar ahead oak
Base HD Path:  m/44'/60'/0'/0/{account_index}

Listening on localhost:8545
/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/solc/bin/soljson-latest.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS

TypeError: Cannot read property 'processNextBlock' of undefined
    at StateManager.mineOnInterval [as _onTimeout] (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/statemanager.js:103:20)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by tcoulter** [comment]
Fixed in v2.2.1. Nice catch!
