### ISSUE TITLE
eth_sendTransaction stucks after an error

### ISSUE THREAD

**Issue by mpolci** [ConsenSys-archive/ganache-cli-archive#147]
After an error, for example for insufficient balance or for an invalid specified nonce, all subsequent calls fails with the same initial error
## Steps to Reproduce (for bugs)

```
truffle(default)> eth=web3.eth

truffle(default)> eth.getBalance(eth.coinbase).toString()
'100000000000000000000'

truffle(default)> eth.sendTransaction({from: eth.coinbase, to: eth.accounts[1], value: 1})
'0xf463d11b8ba94ece43cc3d8d7840fcc29173c60db778a4921f6d8570de5ac1b3'

truffle(default)> eth.sendTransaction({from: eth.coinbase, to: eth.accounts[1], value: eth.getBalance(eth.coinbase) + 1})
Error: Error: sender doesn't have enough funds to send tx. The upfront cost is: 1000000000000004502379 and the senders account only has: 99999999999999978999
    at runCall (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/runTx.js:97:10)
    ...

truffle(default)> eth.getBalance(eth.coinbase).toString()
'99999999999999978999'

truffle(default)> eth.sendTransaction({from: eth.coinbase, to: eth.accounts[1], value: 1})
Error: Error: sender doesn't have enough funds to send tx. The upfront cost is: 1000000000000004502379 and the senders account only has: 99999999999999978999
    at runCall (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/runTx.js:97:10)
    ...

truffle(default)> eth.sendTransaction({from: eth.coinbase, to: eth.accounts[1], value: 5})
Error: Error: sender doesn't have enough funds to send tx. The upfront cost is: 1000000000000004502379 and the senders account only has: 99999999999999978999
    at runCall (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/runTx.js:97:10)
    ...
```

The latest 2 sendTransaction shouldn't fail.

The same with a wrong nonce. After restarted testrpc:

```
truffle(default)> eth.sendTransaction({from: eth.coinbase, to: eth.accounts[1], value: 1, nonce:0})
'0x6233cfb7755dd0bdf9fed7681e7d9412b01103ca49d60cbc4dbffc210091d8ec'
truffle(default)> eth.sendTransaction({from: eth.coinbase, to: eth.accounts[1], value: 1, nonce:1})
'0xfb624d3c593f074afebc5da03089d4a57629ab12d7fb1c251b000108eacb05f5'
truffle(default)> eth.sendTransaction({from: eth.coinbase, to: eth.accounts[1], value: 1, nonce:1})
Error: Error: the tx doesn't have the correct nonce. account has nonce of: 2 tx has nonce of: 1
    at runCall (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/runTx.js:101:10)
    ...
truffle(default)> eth.sendTransaction({from: eth.coinbase, to: eth.accounts[1], value: 1, nonce:2})
Error: Error: the tx doesn't have the correct nonce. account has nonce of: 2 tx has nonce of: 1
    at runCall (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/runTx.js:101:10)
    ...
```
## Your Environment
- Version used: 2.2.2 and 2.2.1
- Operating System and version: Linux ubuntu 16.04

**Comment by mpolci** [comment]
Here a test:

```
    it("recovers after bad nonce", function(done) {
      var request = {
        "jsonrpc": "2.0",
        "method": "eth_sendTransaction",
        "params": [
          {
            "value": "0x10000000",
            "gas": "0xf4240",
            "from": accounts[0],
            "to": accounts[1],
            "nonce": "0xffffffff",  // too big nonce
          }
        ],
        "id": 2
      }
      var provider = web3.currentProvider;
      new Promise(function(resolve, reject) {
        provider.sendAsync(request, resolve);
      })
      .then(() => {
        delete request.params[0].nonce
        provider.sendAsync(request, done)
      })
    });
```

**Comment by tcoulter** [comment]
Interesting bug. Thanks for the test, that was very helpful. I have a fix for the nonce issue incoming. It might also be the same problem affecting the other failed transactions, but I need to test it.

**Comment by tcoulter** [comment]
Great catch! It's now been fixed. v2.2.3 has been released to npm.

Thanks again!
