### ISSUE TITLE
Cannot launch v2.2.7

### ISSUE THREAD

**Issue by xavierlepretre** [ConsenSys-archive/ganache-cli-archive#151]
## Expected Behaviour

When I run `$ testrpc` I expect it to start.
## Current Behaviour

When I run `$ testrpc`, I get:

```
/usr/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/node_modules/solc/bin/soljson-latest.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normaliz

Error: Cannot find module './build/Release/scrypt'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-wallet/node_modules/scrypt.js/node_modules/scrypt/index.js:3:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```
## Steps to Reproduce (for bugs)

``` sh
$ curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
$ sudo apt-get install -y nodejs node-gyp git build-essential
$ npm install -g ethereumjs-testrpc@2.2.7
$ testrpc
```
## Your Environment

``` sh
$ uname -a
Linux vagrant-ubuntu-wily-64 4.2.0-42-generic #49-Ubuntu SMP Tue Jun 28 21:26:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily
```

**Comment by dyzz** [comment]
seems you haven't install node-gyp. Try install node-gyp first, remove node_modules and reinstall

**Comment by xavierlepretre** [comment]
I destroyed and recreated my VM, then did:

``` shell
$ npm install -g node-gyp
$ npm install -g ethereumjs-testrpc@2.2.4
```

Still same issue.
Also with 2.2.7, 2.2.3, 2.2.2, 2.2.1, 2.2.0

**Comment by xavierlepretre** [comment]
Updated the issue as it is still happening on fresh VMs.

**Comment by jmdfm** [comment]
This is an issue with `node-scrypt` not building on your platform: https://github.com/barrysteyn/node-scrypt

Check to see if you can get that module installing on its own first, if not, please raise an issue with the `node-scrypt` team.

**Comment by dendej** [comment]
My workaround is here https://github.com/ethereumjs/testrpc/issues/134

**Comment by benjamincburns** [comment]
It's likely that 2.2.7 is still a pain, but we've since moved on and this should no longer be an issue.
