### ISSUE TITLE
error starting node

### ISSUE THREAD

**Issue by coderwithattitude** [ConsenSys-archive/ganache-cli-archive#159]
Error while starting node on my windows pc
## Expected Behavior

it throughs this error "Secp256k1 bindings are not compiled. Pure JS implementation will be used."
## Steps to Reproduce (for bugs)

1.
2.
3.
4.
## Your Environment

- Version used:
- Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
- Server type and version:
- Operating System and version:
- Link to your project:

**Comment by chevdor** [comment]
Hello @CoderWithAttitude,
It would be great if you could provide more details such as the version you used, the command you typed, etc... If you have a screenshot, that can help too.

You opened #160 and #161 about an installation issue. Did you solve the installation problems before trying to run testrpc?

**Comment by elenadimitrova** [comment]
Experiencing the same issue on OSX after upgrading to OSX Sierra.

Tested with both v2.2.7 and v3.0.0 by running `testrpc`

```
app Elena$ testrpc
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileS

Error: Module version mismatch. Expected 48, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/scrypt/index.js:3:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

Possibly related to https://github.com/cryptocoinjs/secp256k1-node/issues/102

**Comment by elenadimitrova** [comment]
This was solved for me after reinstalling ethereum 

```
brew tap ethereum/ethereum
brew uninstall ethereum
brew install ethereum
```

**Comment by self-reality** [comment]
Same here. Reinstalling ethereum doesn't work. 
nodejs v6.9.1
ubuntu 14.04

```
petr@Lenovo-3000-G550:~$ testrpc
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
/home/petr/.npm-global/lib/node_modules/ethereumjs-testrpc/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeF

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/petr/.npm-global/lib/node_modules/ethereumjs-testrpc/node_modules/scrypt/index.js:3:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

```

**Comment by next-jesusdiazvico** [comment]
I'm having the exact same problem as @porobov.

**Comment by fanatid** [comment]
@porobov @beeva-jesusdiaz remove and install testrpc from scratch
the problem is that scrypt package was compiled with other node version
secp256k1 will work in any case (even if you see message "Secp256k1 bindings are not compiled. Pure JS implementation will be used.")

**Comment by chevdor** [comment]
1. uninstall testrcp: `npm uninstall -g ethreumjs-testrpc`
2. make sure you have node version 6.x or above (if not, fix that first)
3. ensure you delete the old testrpc: `sudo rm -rf /usr/local/lib/node_modules/ethereumjs-testrpc`
4. reinstall: `npm i -g ethereumjs-testrpc`

**Comment by comodoro** [comment]
I got this message with newer node (7.4.0) and with testrpc already running elsehere (which may be irrelevant). Only after reinstalling node to 6.9.5 the correct message about testrpc already running was shown.
