### ISSUE TITLE
Arrow Functions Error on Elementary OS

### ISSUE THREAD

**Issue by chinmayrane** [ConsenSys-archive/ganache-cli-archive#162]
testrpc gets installed perfectly
## Expected Behavior

testrpc should run fine
## Current Behavior

I get the below error,

/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/filters.js:286
    var results = txs.map((tx) => tx.hash)
                                ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/interface.js:4:25)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
## Your Environment
- Version used:latest
- Environment name and version (e.g.):
- Server type and version:
- Operating System and version: Elemetary OS Terminal 0.3 Freya
- Link to your project:

**Comment by chinmayrane** [comment]
Updated Canonical Freya Directories and Node to VERSION 6.5 and then had to globally install memdown. Now it's set up perfectly.
