### ISSUE TITLE
testrpc - Error: Module version mismatch

### ISSUE THREAD

**Issue by ghost** [ConsenSys-archive/ganache-cli-archive#163]
Hello! 

Could not find a solution using Google and do not know where to ask except here. So please understand that I am new to github, Ubuntu and Ethereum :)

When I run --> **testrpc** this Error shows up:

**Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/scrypt/index.js:3:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)**

Guessing it is something with node and npm?

node --version ---> **v6.4.0**
npm -v --->  **3.10.3**

What might be the problem?
Thank you!

**Comment by tcoulter** [comment]
Did you reinstall node recently? If so, try reinstalling the testrpc.

**Comment by ghost** [comment]
@tcoulter 
Yes..
I tried to reinstall testrpc after following this guide:
https://docs.npmjs.com/getting-started/fixing-npm-permissions

**~$ npm install -g ethereumjs-testrpc
/usr/local/bin/testrpc -> /usr/local/lib/node_modules/ethereumjs-testrpc/bin/testrpc
/usr/local/lib
└─┬ ethereumjs-testrpc@2.2.7 
  ├─┬ web3@0.16.0
  │ └── bignumber.js@2.0.7  (git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2)
  └─┬ web3-provider-engine@8.0.4
    └─┬ web3@0.15.3
      └── bignumber.js@2.0.7  (git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2)**

When running testrpc I still get the same error:

~$ testrpc
/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/solc/bin/soljson-latest.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/scrypt/index.js:3:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)

**Comment by ghost** [comment]
Uninstalled everything and then this solved it!

https://steemit.com/ethereum/@brennanhm/ethereum-smart-contract-testing-installing-truffle-and-testrpc

**Comment by chevdor** [comment]
I would love to know what "uninstalled everything" really means...

**Comment by nud3l** [comment]
I guess removing the old nodejs version. On Ubuntu with `sudo apt-get purge nodejs `
