### ISSUE TITLE
Cannot Install OSX Sierra, Node v.6.9, npm 3.10.8, node-gyp 3.4.0

### ISSUE THREAD

**Issue by 360disrupt** [ConsenSys-archive/ganache-cli-archive#185]
Cannot Install OSX Sierra, Node v.6.9, npm 3.10.8, node-gyp 3.4.0

```
npm install -g ethereumjs-testrpc

> scrypt@6.0.3 preinstall /Users/MasterG/.nvm/versions/node/v6.9.0/lib/node_modules/.staging/scrypt-d8c966a3
> node node-scrypt-preinstall.js

/Users/MasterG/.nvm/versions/node/v6.9.0/bin/testrpc -> /Users/MasterG/.nvm/versions/node/v6.9.0/lib/node_modules/ethereumjs-testrpc/bin/testrpc

> scrypt@6.0.3 install /Users/MasterG/.nvm/versions/node/v6.9.0/lib/node_modules/ethereumjs-testrpc/node_modules/scrypt
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: spawn EACCES
gyp ERR! stack     at exports._errnoException (util.js:1026:11)
gyp ERR! stack     at ChildProcess.spawn (internal/child_process.js:313:11)
gyp ERR! stack     at exports.spawn (child_process.js:380:9)
gyp ERR! stack     at exports.execFile (child_process.js:143:15)
gyp ERR! stack     at checkPythonVersion (/Users/MasterG/.nvm/versions/node/v6.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:419:5)
gyp ERR! stack     at /Users/MasterG/.nvm/versions/node/v6.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:361:9
gyp ERR! stack     at /Users/MasterG/.nvm/versions/node/v6.9.0/lib/node_modules/npm/node_modules/which/which.js:88:20
gyp ERR! stack     at /Users/MasterG/.nvm/versions/node/v6.9.0/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /Users/MasterG/.nvm/versions/node/v6.9.0/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/Users/MasterG/.nvm/versions/node/v6.9.0/bin/node" "/Users/MasterG/.nvm/versions/node/v6.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/MasterG/.nvm/versions/node/v6.9.0/lib/node_modules/ethereumjs-testrpc/node_modules/scrypt
gyp ERR! node -v v6.9.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
/Users/MasterG/.nvm/versions/node/v6.9.0/lib
└── (empty)

npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/MasterG/.nvm/versions/node/v6.9.0/bin/node" "/Users/MasterG/.nvm/versions/node/v6.9.0/bin/npm" "install" "-g" "ethereumjs-testrpc"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/MasterG/Projekte/ethereum-bet/npm-debug.log
npm ERR! code 1

```

**Comment by 360disrupt** [comment]
`python -V` gives me `Python 2.7.11`
But somehow the npm configuration was wrong: what helped was: `npm config set python python2.7`

**Comment by detorresvc** [comment]
i have same issue

**Comment by 360disrupt** [comment]
You can query your python installation with `which python` try to use this path here:
`npm config set python <path>` maybe that helps
