### ISSUE TITLE
Contract deployment gas issue

### ISSUE THREAD

**Issue by aakilfernandes** [ConsenSys-archive/ganache-cli-archive#209]
## Expected Behavior
TestRPC should return error (out of gas exception)

## Current Behavior
Transaction hash is returned, transaction receipt is available, but `getCode` is empty

## Steps to Reproduce (for bugs)
1. Deploy a contract without gas

```
web3.eth.sendTransaction({
    data: '0x60606040526001600055600260015534610000575b608c806100216000396000f360606040526000357c010000000000000000000000000000000000000000000000000000000090048063507aff5714604057806367e919b6146060575b6000565b34600057604a6080565b6040518082815260200191505060405180910390f35b34600057606a6086565b6040518082815260200191505060405180910390f35b60015481565b6000548156',
    from: account
}, (err, txHash) => { console.log('err', err, 'txHash', txHash) })
```

2. Get transaction receipt (it will return successfully)
3. Get contract code from reciept's `contractAddress` (it will be an empty)
4. Repeat steps 1, but set gas equal to the block limit
5. Get transaction receipt (it will return successfully)
6. Get contract code from reciept's `contractAddress` (it will **NOT** be an empty)

## Your Environment
OSX, testrpc ^3.0.2

**Comment by benjamincburns** [comment]
@aakilfernandes thanks for the bug!

Just for completeness in our test environment (would like to capture this as a test), can you please also submit the contract code?

**Comment by benjamincburns** [comment]
@aakilfernandes just to clarify as well, you're saying that step 1 should result in an error (out of gas), right? And also that in steps 4-6 the behavior is as expected?

**Comment by benjamincburns** [comment]
I think this is working in the latest version... Tested using `truffle develop` in truffle 4.0 beta:

```
truffle(develop)> web3.eth.sendTransaction({ data: '0x60606040526001600055600260015534610000575b608c806100216000396000f360606040526000357c010000000000000000000000000000000000000000000000000000000090048063507aff5714604057806367e919b6146060575b6000565b34600057604a6080565b6040518082815260200191505060405180910390f35b34600057606a6086565b6040518082815260200191505060405180910390f35b60015481565b6000548156', from: web3.eth.accounts[0] }, (err, txHash) => { console.log('err', err, 'txHash', txHash) })
undefined
truffle(develop)> err Error: VM Exception while processing transaction: out of gas
    at Object.InvalidResponse (/Users/bburns/.nvm/versions/node/v8.7.0/lib/node_modules/truffle/build/cli.bundled.js:37872:16)
    at /Users/bburns/.nvm/versions/node/v8.7.0/lib/node_modules/truffle/build/cli.bundled.js:316805:36
    at /Users/bburns/.nvm/versions/node/v8.7.0/lib/node_modules/truffle/build/cli.bundled.js:294942:9
    at XMLHttpRequest.request.onreadystatechange (/Users/bburns/.nvm/versions/node/v8.7.0/lib/node_modules/truffle/build/cli.bundled.js:315504:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/bburns/.nvm/versions/node/v8.7.0/lib/node_modules/truffle/build/cli.bundled.js:164934:18)
    at XMLHttpRequest._setReadyState (/Users/bburns/.nvm/versions/node/v8.7.0/lib/node_modules/truffle/build/cli.bundled.js:165224:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/bburns/.nvm/versions/node/v8.7.0/lib/node_modules/truffle/build/cli.bundled.js:165379:12)
    at IncomingMessage.<anonymous> (/Users/bburns/.nvm/versions/node/v8.7.0/lib/node_modules/truffle/build/cli.bundled.js:165339:24)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7) txHash undefined
```

**Comment by benjamincburns** [comment]
Closing this one as I think it's working and I haven't heard back from @aakilfernandes
