### ISSUE TITLE
getCompilers

### ISSUE THREAD

**Issue by aakilfernandes** [ConsenSys-archive/ganache-cli-archive#213]
## Expected Behavior
Return array of compilers

## Current Behavior
Returns error

````
ReferenceError: cb is not defined
    at SolcSubprovider.handleRequest (/Users/aakilfernandes/projects/safemarket/solquester/node_modules/web3-provider-engine/subproviders/solc.js:20:7)
    at next (/Users/aakilfernandes/projects/safemarket/solquester/node_modules/web3-provider-engine/index.js:95:18)
    at VmSubprovider.handleRequest (/Users/aakilfernandes/projects/safemarket/solquester/node_modules/web3-provider-engine/subproviders/vm.js:40:12)
    at next (/Users/aakilfernandes/projects/safemarket/solquester/node_modules/web3-provider-engine/index.js:95:18)
    at GethDefaults.handleRequest (/Users/aakilfernandes/projects/safemarket/solquester/node_modules/ethereumjs-testrpc/lib/subproviders/gethdefaults.js:17:12)
    at next (/Users/aakilfernandes/projects/safemarket/solquester/node_modules/web3-provider-engine/index.js:95:18)
    at FilterSubprovider.handleRequest (/Users/aakilfernandes/projects/safemarket/solquester/node_modules/web3-provider-engine/subproviders/filters.js:87:7)
    at next (/Users/aakilfernandes/projects/safemarket/solquester/node_modules/web3-provider-engine/index.js:95:18)
    at DelayedBlockFilter.handleRequest (/Users/aakilfernandes/projects/safemarket/solquester/node_modules/ethereumjs-testrpc/lib/subproviders/delayedblockfilter.js:27:3)
    at next (/Users/aakilfernandes/projects/safemarket/solquester/node_modules/web3-provider-engine/index.js:95:18)
    at ReactiveBlockTracker.handleRequest (/Users/aakilfernandes/projects/safemarket/solquester/node_modules/ethereumjs-testrpc/lib/subproviders/reactiveblocktracker.js:25:12)
    at next (/Users/aakilfernandes/projects/safemarket/solquester/node_modules/web3-provider-engine/index.js:95:18)
    at RequestFunnel.handleRequest (/Users/aakilfernandes/projects/safemarket/solquester/node_modules/ethereumjs-testrpc/lib/subproviders/requestfunnel.js:32:12)
    at next (/Users/aakilfernandes/projects/safemarket/solquester/node_modules/web3-provider-engine/index.js:95:18)
    at Web3ProviderEngine._handleAsync (/Users/aakilfernandes/projects/safemarket/solquester/node_modules/web3-provider-engine/index.js:82:3)
    at /Users/aakilfernandes/projects/safemarket/solquester/node_modules/web3-provider-engine/node_modules/async/dist/async.js:1008:9
    at eachOfArrayLike (/Users/aakilfernandes/projects/safemarket/solquester/node_modules/web3-provider-engine/node_modules/async/dist/async.js:941:9)
    at eachOf (/Users/aakilfernandes/projects/safemarket/solquester/node_modules/web3-provider-engine/node_modules/async/dist/async.js:991:5)
    at _asyncMap (/Users/aakilfernandes/projects/safemarket/solquester/node_modules/web3-provider-engine/node_modules/async/dist/async.js:1006:5)
    at Object.map (/Users/aakilfernandes/projects/safemarket/solquester/node_modules/web3-provider-engine/node_modules/async/dist/async.js:996:16)
    at Timeout._onTimeout (/Users/aakilfernandes/projects/safemarket/solquester/node_modules/web3-provider-engine/index.js:63:13)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
````
## Your Environment
MacOSx, ^3.0.2

**Comment by tcoulter** [comment]
Man, you're really poking (good) holes in TestRPC lately. I assume this should be an easy fix, as "solidity" is the only one. I'd guess there's not a test for this request.

**Comment by aakilfernandes** [comment]
Yup! I'm working on a fix. I've actually been working on a web3 alternative, hence all the testrpc poking =)

**Comment by aakilfernandes** [comment]
@tcoulter this should get fixed when https://github.com/MetaMask/provider-engine/pull/99 gets merged.

**Comment by axic** [comment]
Please avoid using `eth_compile`, it doesn't really belong to the RPC.

`solc-js` should be used directly in the web3.js alternative - gives much more flexibility too.

**Comment by benjamincburns** [comment]
At the moment we return `['solidity']` however this should be a null array as we no longer support `eth_compileSolidity`

**Comment by mikeseese** [comment]
Closing this in favor of https://github.com/trufflesuite/ganache-core/issues/139
