### ISSUE TITLE
NODE_MODULE_VERSION mismatch

### ISSUE THREAD

**Issue by waglik** [ConsenSys-archive/ganache-cli-archive#227]
When running testrpc I get this error : 

The module '/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/scrypt/build/Release/scrypt.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/scrypt/index.js:3:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

node version : 4.2.6
npm version : 3.5.2 

test-rpc version : 3.0.3

any hints how to fix this?

**Comment by fanatid** [comment]
This error related with https://github.com/barrysteyn/node-scrypt not with testrpc.
But as I assume you install scrypt globally with other node version, try remove and install testrpc from scratch.

**Comment by waglik** [comment]
I had to remove node-script folder manually and installing testrpc again but that solved the issue. thanks
