### ISSUE TITLE
Secp256k1 bindings are not compiled. Pure JS implementation will be used.

### ISSUE THREAD

**Issue by Zihin** [ConsenSys-archive/ganache-cli-archive#271]
Ubuntu 16.04
```
ace@ace-virtual-machine:~$ nodejs --version
v6.10.0
```

```
ace@ace-virtual-machine:~$ npm --version
4.4.0
```

```
ace@ace-virtual-machine:~$ testrpc
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
/usr/lib/node_modules/ethereumjs-testrpc/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](

Error: Cannot find module './build/Release/scrypt'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/ethereumjs-testrpc/node_modules/scrypt/index.js:3:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Secp256k1 bindings are not compiled. Pure JS implementation will be used.
Why I encountered this problem? Does anyone meet this? How to solove it?
Thanks!

**Comment by lucailvec** [comment]
try to install scrypt manually :
`npm install -g scrypt`

**Comment by Hannoverrunner** [comment]
Same here on Ubuntu 16.04 with node v6.10.3 and npm v4.5.0, regarding the Secp256k1 bindings.

My error log however is different,

```
alex@vbox:~$ testrpc
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileS

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/scrypt/index.js:3:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

Did try to search for similar cases regarding either the Secp256k1 message or the module version error. Didn't find anything leading to a solution yet.

Any help is much appreciated.

**Comment by fanatid** [comment]
@ShreksEsel please read error messages more attentive, `scrypt` is not compiled on your machine<s>, not `secp256k1`</s>. You need reinstall `node_modules`.

**Comment by Powersource** [comment]
@fanatid That might solve that problem but not the one this issue is about, are you sure this issue should be closed?

**Comment by fanatid** [comment]
@Powersource there no "might", this should solve problem, but thanks in any case, it made me rethink my words above

If you see `Secp256k1 bindings are not compiled. Pure JS implementation will be used.` this means that `secp256k1` is not compiled, but pure js implementation will be used, so you see only warning (probably `secp256k1` should show this only if `process.env.DEBUG` is set).

Check error stack:
First you can see `Module version mismatch. Expected 48, got 46.` what this means? Node.js was updated to new major version, in current case from 4.x to 6.x (you can find versions here https://nodejs.org/en/download/releases/)
Then you can see line `at Object.<anonymous> (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/scrypt/index.js:3:20)` which clearly tell us that error was thrown from `scrypt` package.

With this facts we can say with 100% probability that reinstalling solve problem.
