### ISSUE TITLE
Error Installing on Windows

### ISSUE THREAD

**Issue by ShakreeElmi** [ConsenSys-archive/ganache-cli-archive#274]
Followed step by step of the installation instruction from the wiki, however testrpc is unable to be installed. Following is the error I receive:

```
C:\WINDOWS\system32>npm install -g ethereumjs-testrpc

> scrypt@6.0.3 preinstall C:\Users\MohdShakreeElmi\AppData\Roaming\npm\node_modules\.staging\scrypt-09e6fdc5
> node node-scrypt-preinstall.js

C:\Users\MohdShakreeElmi\AppData\Roaming\npm\testrpc -> C:\Users\MohdShakreeElmi\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\bin\testrpc

> scrypt@6.0.3 install C:\Users\MohdShakreeElmi\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\scrypt
> node-gyp rebuild


C:\Users\MohdShakreeElmi\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Users\MohdShakreeElmi\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\Users\MohdShakreeElmi\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\scrypt\build\..\scrypt\win\include\config.h
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : warning MSB4010: The "*.tasks" files could not be successfully loaded
 from their expected location "C:\Windows\Microsoft.NET\Framework\v2.0.50727".
Default tasks will not be available.  [C:\Users\MohdShakreeElmi\AppData\Roaming
\npm\node_modules\ethereumjs-testrpc\node_modules\scrypt\build\binding.sln]
MSBUILD : error MSB4036: The "Message" task was not found. Check the following:
 1.) The name of the task in the project file is the same as the name of the ta
sk class. 2.) The task class is "public" and implements the Microsoft.Build.Fra
mework.ITask interface. 3.) The task is correctly declared with <UsingTask> in
the project file, or in the *.tasks files located in the "C:\Windows\Microsoft.
NET\Framework\v2.0.50727" directory. [C:\Users\MohdShakreeElmi\AppData\Roaming\
npm\node_modules\ethereumjs-testrpc\node_modules\scrypt\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\MohdShakreeElmi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\MohdShakreeElmi\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\MohdShakreeElmi\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\scrypt
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
C:\Users\MohdShakreeElmi\AppData\Roaming\npm
`-- (empty)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MohdShakreeElmi\AppData\Roaming\npm-cache\_logs\2017-03-08T00_46_58_955Z-debug.log
```

[2017-03-08T00_46_58_955Z-debug.txt](https://github.com/ethereumjs/testrpc/files/826300/2017-03-08T00_46_58_955Z-debug.txt)

**Comment by en-tropyc** [comment]
Same issue

**Comment by jessicagmarshall** [comment]
same

**Comment by DeviateFish** [comment]
I believe this just means you need to install `python`

**Comment by tcoulter** [comment]
Can all of you give the TestRPC `beta` a try? First uninstall the normal one, if installed (or partially installed):

```
$ npm uninstall -g ethereumjs-testrpc
```

And then install the beta version: 

```
$ npm install -g ethereumjs-testrpc
```

The beta version significantly improves installation and should bypass your installation issues. 

Since this is a beta version, I'd very much appreciate feedback on how it works for you and if you run into any errors during use.

**Comment by benjamincburns** [comment]
We've had great feedback from Windows users of TestRPC since we made the switch to webpack, so I think it's safe to close this one.
