### ISSUE TITLE
Testrpc issue with Mist

### ISSUE THREAD

**Issue by mariam-crissi** [ConsenSys-archive/ganache-cli-archive#292]
I have developed a dapp.I am trying to run the dapp using Mist and testrpc.

## Steps to Reproduce 

1.   Start testrpc
2.   Start mist with --rpc localhost:8545
3.   Select any account and try to send ether

## Current Behavior
I have opened the dapp using localhost:8080..It shows the dapp home page...But while I am trying to send a transaction it returns out of gas exception...

```
It seems this transaction will fail. If you submit it, it may consume all the gas you send.
```
and

```
Estimated fee consumption: We couldn't estimate the gas.
```

In the console it prints the following.

```
[2017-04-11 15:27:27.948] [INFO] (ui: browser) - Connect to node...
[2017-04-11 15:43:21.082] [INFO] (ui: browser) - Trivandrum
[2017-04-11 15:43:21.087] [INFO] (ui: browser) - Chennai
[2017-04-11 15:43:21.088] [INFO] (ui: browser) - 2
[2017-04-11 15:43:21.092] [INFO] (ui: browser) - 2017-04-13
[2017-04-11 15:43:21.093] [INFO] (ui: browser) - 12:00
[2017-04-11 15:43:21.093] [INFO] (ui: browser) - Function - userValidation
[2017-04-11 15:43:21.094] [INFO] (ui: browser) - Function - userDateTimeCreator
[2017-04-11 15:43:21.094] [INFO] (ui: browser) - DateTime for input 2017-04-13 09:00:00
[2017-04-11 15:43:21.095] [INFO] (ui: browser) - Function-distanceRetrieval
[2017-04-11 15:43:21.095] [INFO] (ui: browser) - Trivandrum|Chennai
[2017-04-11 15:43:21.124] [INFO] (ui: browser) - Initializing distanceRetrieval function
[2017-04-11 15:43:21.154] [INFO] method/eth_sendTransaction - Ask user for password
[2017-04-11 15:43:21.154] [INFO] method/eth_sendTransaction - { from: '0x0d1b50c4cbe8e19ae5f08c04ff36581eb77a31b1',
  gas: '0x2dc6c0',
  value: '0xde0b6b3a7640000',
  to: '0xca10adf31afd5e05d3491ca67f13b9e1d2f5589d',
  data: '0x0f77c48c0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001254726976616e6472756d7c4368656e6e61690000000000000000000000000000' }
[2017-04-11 15:43:21.195] [INFO] Windows - Create popup window: sendTransactionConfirmation
[2017-04-11 15:43:21.196] [INFO] Windows - Create secondary window: sendTransactionConfirmation, owner: notset
[2017-04-11 15:43:21.251] [INFO] (ui: browser) - Initializing weatherconditionRetrieval function
[2017-04-11 15:43:21.280] [INFO] method/eth_sendTransaction - Ask user for password
[2017-04-11 15:43:21.281] [INFO] method/eth_sendTransaction - { from: '0x0d1b50c4cbe8e19ae5f08c04ff36581eb77a31b1',
  gas: '0x2dc6c0',
  value: '0xde0b6b3a7640000',
  to: '0xca10adf31afd5e05d3491ca67f13b9e1d2f5589d',
  data: '0x2bb7205d0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000074368656e6e6169000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000013323031372d30342d31332030393a30303a303000000000000000000000000000' }
[2017-04-11 15:43:21.285] [INFO] Windows - Create popup window: sendTransactionConfirmation
[2017-04-11 15:43:22.224] [INFO] Sockets/7 - Connect to {"hostPort":"localhost:8545"}
[2017-04-11 15:43:22.230] [INFO] Sockets/7 - Connected!
[2017-04-11 15:43:23.537] [INFO] (ui: popupWindow) - Web3 already initialized, re-using provider.
[2017-04-11 15:43:23.874] [ERROR] ipcProviderBackend - Send request failed { message: 'Error: tx has a higher gas limit than the block\n    at VM.module.exports [as runTx] (/home/toshiba/.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/runTx.js:35:8)\n    at VmSubprovider.runVm (/home/toshiba/.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/vm.js:106:6)\n    at VmSubprovider.handleRequest (/home/toshiba/.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/vm.js:45:8)\n    at next (/home/toshiba/.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)\n    at GethDefaults.handleRequest (/home/toshiba/.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/lib/subproviders/gethdefaults.js:34:5)\n    at next (/home/toshiba/.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)\n    at FilterSubprovider.handleRequest (/home/toshiba/.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/filters.js:87:7)\n    at next (/home/toshiba/.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)\n    at DelayedBlockFilter.handleRequest (/home/toshiba/.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/lib/subproviders/delayedblockfilter.js:27:3)\n    at next (/home/toshiba/.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)',
  code: -32000 }
[2017-04-11 15:43:24.121] [INFO] (ui: popupWindow) - Estimated gas:  null {}
[2017-04-11 15:43:24.172] [ERROR] ipcProviderBackend - Send request failed { message: 'Error: tx has a higher gas limit than the block\n    at VM.module.exports [as runTx] (/home/toshiba/.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/runTx.js:35:8)\n    at VmSubprovider.runVm (/home/toshiba/.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/vm.js:106:6)\n    at VmSubprovider.handleRequest (/home/toshiba/.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/vm.js:45:8)\n    at next (/home/toshiba/.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)\n    at GethDefaults.handleRequest (/home/toshiba/.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/lib/subproviders/gethdefaults.js:34:5)\n    at next (/home/toshiba/.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)\n    at FilterSubprovider.handleRequest (/home/toshiba/.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/filters.js:87:7)\n    at next (/home/toshiba/.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)\n    at DelayedBlockFilter.handleRequest (/home/toshiba/.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/lib/subproviders/delayedblockfilter.js:27:3)\n    at next (/home/toshiba/.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)',
  code: -32000 }
[2017-04-11 15:43:24.251] [INFO] (ui: popupWindow) - Estimated gas:  null {}

```

Any idea

**Comment by xoriole** [comment]
Any update on this issue?

**Comment by rohithpr** [comment]
`mist --rpc http://localhost:8545` works for me when I'm using testrpc.

**Comment by synacker** [comment]
The same issue. Mist version is 0.8.10. geth version is 1.6.6.

**Comment by surfer77** [comment]
Any updates on this? have the same issue

**Comment by dabdevelop** [comment]
testrpc does not even has a password for account.

**Comment by benjamincburns** [comment]
Related to #236.

**Comment by mikeseese** [comment]
Closing in favor of #236
