### ISSUE TITLE
calls() don't work if not from a node address

### ISSUE THREAD

**Issue by simondlr** [ConsenSys-archive/ganache-cli-archive#3]
For a call(), the "from" address is optional.

But testrpc fails when using another "from" address. Notably when using hookedweb3provider in a lightwallet.

```
/usr/local/lib/node_modules/ethereumjs-testrpc/lib/blockchain.js:469
  var privateKey = new Buffer(this.accounts[from].secretKey, 'hex');
                                                 ^
TypeError: Cannot read property 'secretKey' of undefined
    at Blockchain.processCall (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/blockchain.js:469:50)
    at Blockchain.processNextAction (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/blockchain.js:356:10)
    at Blockchain.queueAction (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/blockchain.js:322:8)
    at Blockchain.queueCall (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/blockchain.js:255:8)
    at Manager.eth_call (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/manager.js:83:19)
    at wrapped (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/server.js:39:8)
    at eval (eval at giveArity (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/server.js:21:41), <anonymous>:1:29)
    at Method.execute (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/jayson/lib/method.js:129:22)
    at /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/jayson/lib/server.js:290:12
    at maybeParse (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/jayson/lib/server.js:407:5)
    at Server.call (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/jayson/lib/server.js:235:3)
```

calls should be able to take an arbitrary address to use as tx.origin.

**Comment by kumavis** [comment]
as an aside, the default behaviour is not specified in the json rpc wiki, we should see how geth and others react to an ORIGIN opcode when the from is not specified

**Comment by simondlr** [comment]
fwiw, geth can receive an arbitrary from address (that's not in the nodes). It will use that as if that's tx.origin for a call().

**Comment by kumavis** [comment]
@simondlr good to know! thanks

**Comment by tcoulter** [comment]
Added to v0.2.0 milestone (next release)

**Comment by tcoulter** [comment]
This should be fixed. Closing. Please reopen if I'm incorrect.
