### ISSUE TITLE
Bump Node Version to 7.9.0 in Dockerfile

### ISSUE THREAD

**Issue by nickgs** [ConsenSys-archive/ganache-cli-archive#302]
The Dockerfile in the 3.x branch is using Node 5.10. As of testrpc version 3.0.2 we need to be using at least 6.9.1. As a result the running testrpc is resulting in the following error on startup: 

function VM (opts = {}) {
                  ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/src/node_modules/ethereumjs-vm/lib/hooked.js:6:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

## Expected Behavior

Able to run Testrpc successfully without crashing.

## Current Behavior

Testrpc is crashing on startup.

## Possible Solution

Bump the version in the Dockerfile to 7.9.0. 

## Steps to Reproduce (for bugs)

1. Run `docker build -t testrpc .` with in the project root.
2. Run `docker run -p 8545:8545 testrpc`

## Your Environment

* Mac
* Testrpc 3.0.3

**Comment by veox** [comment]
Issue can be closed?

**Comment by nickgs** [comment]
I believe so. This has been merged. 

Closing.
