### ISSUE TITLE
Release/scrypt.node: undefined symbol

### ISSUE THREAD

**Issue by dotnetspec** [ConsenSys-archive/ganache-cli-archive#308]
## Expected Behavior
testrpc starts without error

## Current Behavior
error as per terminal output below

## Possible Solution
Google search not helpful

## Steps to Reproduce (for bugs)
1.'testrpc' at command prompt

## Context
How has this issue affected you? Unable to start testrpc

What are you trying to accomplish? start testrpc
I recently, last couple of days, downloaded and installed

## Your Environment

* Version used: how to determine version?
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): how to determine version?
* Server type and version: Dell Inspiron-1525 
* Operating System and version: Linux Mint 18
* Link to your project: N/a

TERMINAL OUTPUT:
philip@philip-Inspiron-1525 ~/Projects/Dapp Projects/Truffle $ testrpc
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileS

Error: /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/scrypt/build/Release/scrypt.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEi
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/scrypt/index.js:3:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
philip@philip-Inspiron-1525 ~/Projects/Dapp Projects/Truffle $

**Comment by dotnetspec** [comment]
Fixed by following:
error starting node #159
