### ISSUE TITLE
TypeError: Invalid entropy................Error installation of testrpc

### ISSUE THREAD

**Issue by capamaster** [ConsenSys-archive/ganache-cli-archive#313]
## Expected Behavior
~> testrpc to run..........

## Current Behavior
testrpc 
/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileS

TypeError: Invalid entropy
    at Object.entropyToMnemonic (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/bip39/index.js:94:37)
    at new StateManager (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/statemanager.js:45:45)
    at new GethApiDouble (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/subproviders/geth_api_double.js:17:33)
    at Object.Interface.provider (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/interface.js:160:25)
    at Object.Interface.server (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/interface.js:28:25)
    at Object.TestRPC.server (/usr/local/lib/node_modules/ethereumjs-testrpc/index.js:5:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/ethereumjs-testrpc/bin/testrpc:70:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)

## Steps to Reproduce (for bugs)
 sudo npm install -g ethereumjs-testrpc@2.2.4

## Your Environment
* Version used: 
node - v6.4.0
npm -  3.10.3

* Operating System and version: Ubuntu 14.04
* Link to your project:

Kindly help.................

**Comment by kevsul** [comment]
It's an incompatibility with the latest version (2.3.1) of bip39 lib. 
You can get around it by explicitly adding version 2.3.0 of bip39 lib to your package.json before ethereumjs-testrpc e.g.
```
"devDependencies": {
    "bip39": "2.3.0",
    "ethereumjs-testrpc": "^2.2.4",
```

**Comment by benjamincburns** [comment]
@capamaster I'm so sorry this went for so long without a response! I think this is no longer an issue in the latest TestRPC (v6.0.2). If I'm mistaken, please reopen.
