### ISSUE TITLE
NPM install Failed

### ISSUE THREAD

**Issue by IAMtheIAM** [ConsenSys-archive/ganache-cli-archive#319]
`npm install -g ethereumjs-testrpc` makes error during install

```
C:\Source>npm install -g ethereumjs-testrpc@latest

> scrypt@6.0.3 preinstall C:\Users\k\AppData\Roaming\npm\node_modules\.staging\scrypt-edfcd54c
> node node-scrypt-preinstall.js

C:\Users\nparson\AppData\Roaming\npm\testrpc -> C:\Users\nparson\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\bin\testrpc

> scrypt@6.0.3 install C:\Users\k\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\scrypt
> node-gyp rebuild


C:\Users\k\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Users\k\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\Users\k\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\scrypt\build\..\scrypt\win\include\config.h
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Copying scrypt/win/include/config.h to scrypt/scrypt-1.2.0/config.h
  The system cannot find the file specified.
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\k\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\scrypt\build\copied_files.vcxproj]


TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\k\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\scrypt\build\scrypt_wrapper.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\k\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\dev\\nodejs\\node.exe" "C:\\Users\\k\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\k\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\scrypt
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
```

Ran from both powershell and administrative command prompt gives the same error. Windows 10x64. Python 2.7 and windows 8.1 sdk both installed.

**Comment by IAMtheIAM** [comment]
I  ran `npm config set msvs_version 2015 --global`

Now I get

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v120 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, please install v120 build tools. 
Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\k\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\scrypt\build\copied_files.vcxproj]
```

I have platform tools v140 installed, how do I make it use v140 instead of v120. This is frustrating

**Comment by IAMtheIAM** [comment]
Solution was to install Open visual studio 2015,. create a new C++ project then install the build tools. See the picture for the build tools that needed to be installed.

![2017-06-13_1040](https://user-images.githubusercontent.com/13709948/27096735-e521c8b2-5026-11e7-8fbe-5033a289f40d.png)

**Comment by tcoulter** [comment]
Hi there. Thanks for the updates. Can you check out [this post](http://truffleframework.com/blog/removing-installation-issues-continued-testrpc) we just published? We've completely reworked the TestRPC removing most if not all installation issues. Thanks!

**Comment by RichLinnell** [comment]
I tried the beta installation process after experiencing similar issues to the original post above.  The installation went fine, but when I call testrpc I receive the following error :
```
function VM (opts = {}) {
                  ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

**Comment by RichLinnell** [comment]
I moved across to my Mac in the end.  All ran very simply here.  Think Win 10 is not there yet.

**Comment by ponarunkumar** [comment]
In Ubuntu 16.04, I am encountering issues with the installation. any help is much appreciated.
uspace@uspace-VirtualBox:~$ sudo npm install -g ethereumjs-testrpc
[sudo] password for uspace: 
npm ERR! git clone --template=/home/uspace/.npm/_git-remotes/_templates --mirror https://github.com/debris/bignumber.js.git /home/uspace/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1: Cloning into bare repository '/home/uspace/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1'...
npm ERR! git clone --template=/home/uspace/.npm/_git-remotes/_templates --mirror https://github.com/debris/bignumber.js.git /home/uspace/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1: remote: Invalid username or password.
npm ERR! git clone --template=/home/uspace/.npm/_git-remotes/_templates --mirror https://github.com/debris/bignumber.js.git /home/uspace/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1: fatal: Authentication failed for 'https://github.com/debris/bignumber.js.git/'
npm ERR! Linux 4.8.0-56-generic
npm ERR! argv "/opt/node/bin/node" "/usr/bin/npm" "install" "-g" "ethereumjs-testrpc"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/uspace/.npm/_git-remotes/_templates --mirror https://github.com/debris/bignumber.js.git /home/uspace/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1
npm ERR! Cloning into bare repository '/home/uspace/.npm/_git-remotes/git-https-github-com-debris-bignumber-js-git-master-df3f1ce1'...
npm ERR! remote: Invalid username or password.
npm ERR! fatal: Authentication failed for 'https://github.com/debris/bignumber.js.git/'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/uspace/npm-debug.log

**Comment by mikeseese** [comment]
Closing due to inactivity/age
