### ISSUE TITLE
Gas costs are incorrect

### ISSUE THREAD

**Issue by TripleSpeeder** [ConsenSys-archive/ganache-cli-archive#324]
While working on another contract i found there is an issue with calculation of gas costs. It looks like somewhere testrpc is using hardcoded value of 100000000000 wei for gasprice, no matter what is specified on command line or default value.

## Expected Behavior
The gas costs of a transaction should be calculated correctly based on gas used and gas price.

## Current Behavior
The gas costs are always calculated based on a gasprice of 100000000000 wei.

#### simple test contract:
```pragma solidity ^0.4.0;

contract Gastest {

    string public someString;

    function Gastest(){}

    function setString(string newString) {
        someString = newString;
    }
}
```
#### Unittest:
```
var Gastest = artifacts.require("./Gastest.sol")

contract('Gastest', function (accounts) {
    let account = accounts[0]
    let startBalance
    let gastestInstance
    let gasUsed

    before('Get contract instance', function () {
        return Gastest.deployed().then(function (instance) {
            gastestInstance = instance
        })
    })

    before('Get current balance', function () {
        // get current balance
        startBalance = web3.eth.getBalance(account)
        assert.isAbove(startBalance.toNumber(), web3.toWei(10, 'ether'))
        console.log("Account startbalance: " + startBalance.toString())
    })

    it("Should set a new string and get gas used", function () {
        return gastestInstance.setString("Just a test", {from: account}).then(function (result) {
            assert.isNotNull(result.receipt.blockHash)
            assert.isNotNull(result.receipt.blockNumber)
            gasUsed = result.receipt.gasUsed
            assert.isNumber(gasUsed)
            console.log("Gas used according to receipt: " + gasUsed)
        })
    })

    it("should use correct gasprice", function () {
        let newBalance = web3.eth.getBalance(account)
        let transactionCosts = startBalance.minus(newBalance)
        let actualGasPrice = transactionCosts.div(gasUsed)
        let web3GasPrice = web3.eth.gasPrice
        console.log("Calculated gasprice: " + actualGasPrice.toString())
        console.log("web3 gasprice      : " + web3GasPrice.toString())
        assert(actualGasPrice.equals(web3GasPrice))
    })

})
```
### Test fails when starting testrpc with default values
1. Start testrpc: 
> [michael@stingray gasbug]$ testrpc
> ...

2. Run truffle tests:
> [michael@stingray gasbug]$ truffle test
> Using network 'development'.
>
>
>
>  Contract: Gastest
> Account startbalance: 99899335400000000000
> Gas used according to receipt: 43192
>     ✓ Should set a new string and get gas used
> Calculated gasprice: 100000000000
> web3 gasprice      : 20000000000
>     1) should use correct gasprice
>     > No events were emitted
> 
> 
>   1 passing (287ms)
>   1 failing
> 
>   1) Contract: Gastest should use correct gasprice:
>      AssertionError: Unspecified AssertionError
>       at Context.<anonymous> (test/TestGasPrice.js:39:9)

### Test fails when starting testrpc with random gasprice
1. Start testrpc: 
> [michael@stingray gasbug]$ testrpc -g 3000000
> ...
> Gas Price
> 3000000
> ...

2. Run truffle tests:
> [michael@stingray gasbug]$ truffle test
> Using network 'development'.
> 
> 
> 
>   Contract: Gastest
> Account startbalance: 99899335400000000000
> Gas used according to receipt: 43192
>     ✓ Should set a new string and get gas used
> Calculated gasprice: 100000000000
> web3 gasprice      : 3000000
>     1) should use correct gasprice
>     > No events were emitted
> 
> 
>   1 passing (293ms)
>   1 failing
> 
>   1) Contract: Gastest should use correct gasprice:
>      AssertionError: Unspecified AssertionError
>       at Context.<anonymous> (test/TestGasPrice.js:39:9)

### Test succeeds when starting testrpc with gasprice of 100000000000 wei
1. Start testrpc:
> [michael@stingray gasbug]$ testrpc -g 100000000000
> ...
> Gas Price
> 100000000000
> ...

2. Run truffle tests:
> [michael@stingray gasbug]$ truffle test
> Using network 'development'.
> 
> 
> 
>   Contract: Gastest
> Account startbalance: 99951827300000000000
> Gas used according to receipt: 43192
>     ✓ Should set a new string and get gas used (42ms)
> Calculated gasprice: 100000000000
> web3 gasprice      : 100000000000
>     ✓ should use correct gasprice (151ms)
> 
> 
>   2 passing (294ms)

## Your Environment
* Version used: EthereumJS TestRPC v3.9.2, running on arch linux.

**Comment by TripleSpeeder** [comment]
Additional notes:
* I'm pretty sure this happend also with previous versions of testRPC.
* Workaround for the moment: Always run testrpc with a gasprice of 100000000000 wei ("-g 100000000000")

**Comment by TripleSpeeder** [comment]
Okay, disregard this issue. I was badly mixing up meaning of web3.eth.gasPrice, the gasPrice parameter of testrpc and the fact that the user can/should provide the gasprice he wants to pay with every transaction.
Totally invalid :-)
