### ISSUE TITLE
Migrations failed due to internal truffle bug

### ISSUE THREAD

**Issue by mezrin** [ConsenSys-archive/ganache-cli-archive#326]
Failed to make migration after the previous launch failed.

For example, we have 5 migration steps.
First 3 finished successfully, 4nd failed. We launch migration again - internal truffle error crashes the process

the problem is in the file: `/usr/lib/node_modules/truffle/node_modules/truffle-migrate/index.js`, line 205.

There is a line `return migrations.last_completed_migration.call();` but should be `return migrations.lastCompletedMigration.call();` 

Without this fix I see the error message:

```
Running migration: 2_deploy_api.js
  Start migration
  Running step...
  Deploying UsersRepository ...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: invalid address
    at inputAddressFormatter (/usr/lib/node_modules/truffle/node_modules/web3/lib/web3/formatters.js:271:11)
    at inputTransactionFormatter (/usr/lib/node_modules/truffle/node_modules/web3/lib/web3/formatters.js:97:20)
    at /usr/lib/node_modules/truffle/node_modules/web3/lib/web3/method.js:89:28
    at Array.map (native)
    at Method.formatInput (/usr/lib/node_modules/truffle/node_modules/web3/lib/web3/method.js:88:32)
    at Method.toPayload (/usr/lib/node_modules/truffle/node_modules/web3/lib/web3/method.js:114:23)
    at Eth.send [as sendTransaction] (/usr/lib/node_modules/truffle/node_modules/web3/lib/web3/method.js:139:30)
    at ContractFactory.new (/usr/lib/node_modules/truffle/node_modules/web3/lib/web3/contract.js:214:22)
    at /usr/lib/node_modules/truffle/node_modules/truffle-contract/contract.js:378:30
    at /usr/lib/node_modules/truffle/node_modules/truffle-contract/contract.js:348:16
```

Truffle version 3.2.5, Ubuntu 16.04

**Comment by gnidan** [comment]
@mezrin are you still experiencing this issue?

**Comment by gnidan** [comment]
Closing for issue maintenance. Please open a new issue if the problem persists. Thanks!
