### ISSUE TITLE
Testrpc exits with an error

### ISSUE THREAD

**Issue by rstormsf** [ConsenSys-archive/ganache-cli-archive#340]
https://github.com/MetaMask/metamask-plugin/issues/1702

Steps:
Open metamask,
Select token's page

```
eth_getTransactionCount
eth_getCode
eth_getBalance
eth_getTransactionCount
eth_getCode
eth_getBalance
eth_getTransactionCount
eth_getCode
eth_getBalance
eth_getTransactionCount
eth_getCode
eth_getBlockByNumber
eth_getBlockByNumber
eth_getBalance
eth_getTransactionCount
eth_getBalance
eth_getTransactionCount
eth_getBalance
eth_getTransactionCount
eth_getBalance
eth_getTransactionCount
/Users/rstorm/.nvm/versions/node/v7.10.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:61262
    db.get(key, {
      ^

TypeError: Cannot read property 'get' of undefined
    at dbGet (/Users/rstorm/.nvm/versions/node/v7.10.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:61262:7)
    at /Users/rstorm/.nvm/versions/node/v7.10.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:17720:5
    at /Users/rstorm/.nvm/versions/node/v7.10.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:24532:20
    at iterate (/Users/rstorm/.nvm/versions/node/v7.10.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:24613:13)
    at /Users/rstorm/.nvm/versions/node/v7.10.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:24625:29
    at /Users/rstorm/.nvm/versions/node/v7.10.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:24395:16
    at /Users/rstorm/.nvm/versions/node/v7.10.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:17725:7
    at /Users/rstorm/.nvm/versions/node/v7.10.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:61267:9
    at dispatchError (/Users/rstorm/.nvm/versions/node/v7.10.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:31665:35)
    at /Users/rstorm/.nvm/versions/node/v7.10.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:23916:14
```

* Version used: 4.0.1
* Operating System and version: OSX

**Comment by EdgarCloggs** [comment]
I am hitting this as well. Seems to be happening when: testrpc has a -b <value> set. I have observed that it seems to happen less or not at all without -b. Most likely an issue with testrpcs automatic mining parameter. -b or --blocktime: Specify blocktime in seconds for automatic mining. Default is 0 and no auto-mining.
```

eth_call
/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:61262
    db.get(key, {
      ^
TypeError: Cannot read property 'get' of undefined
    at dbGet (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:61262:7)
```

**Comment by robertsdotpm** [comment]
I'm getting the same error. It's a pain, having to constantly restart a crashed process

**Comment by miguelmota** [comment]
Having same issue.

@rstormsf did you ever figure out a workaround?

**Comment by nacmonad** [comment]
bumperooo   i want the -b but its annoying to restart every 20 min :|

**Comment by LiorRabin** [comment]
Having same issue, also with -b flag on.

I'm running testrpc using forever so it will restart by without me needing to do it :)

Did anyone figure out a workaround for this?

**Comment by benjamincburns** [comment]
I'm consolidating reports of this issue over on #417 - I'll make a note of interval mining being an aggravating factor over there.
