### ISSUE TITLE
eth_getLogs not working 

### ISSUE THREAD

**Issue by wighawag** [ConsenSys-archive/ganache-cli-archive#362]
I want to use eth_getLogs command but I get the following error : 

```
 message : TypeError: Cannot read property 'filter' of undefined
    at C:\Users\wighawag\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\lib\statemanager.js:508:31
    at BlockchainDouble.getBlockLogs (C:\Users\wighawag\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\lib\blockchain_double.js:540:3)
    at C:\Users\wighawag\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\lib\statemanager.js:504:21
    at C:\Users\wighawag\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\async\lib\async.js:787:21
    at C:\Users\wighawag\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\async\lib\async.js:167:37
    at C:\Users\wighawag\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\lib\statemanager.js:528:7
    at BlockchainDouble.getBlockLogs (C:\Users\wighawag\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\lib\blockchain_double.js:540:3)
    at C:\Users\wighawag\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\lib\statemanager.js:504:21
    at Object.async.whilst (C:\Users\wighawag\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\async\lib\async.js:792:13)
    at StateManager.getLogs (C:\Users\wighawag\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\lib\statemanager.js:501:9),
        code : -32000
```

This is using 

```
web3.currentProvider.sendAsync({
 method: "eth_getLogs",
 params: [{
	fromBlock : fromBlock,
        toBlock : toBlock,
  		address:address,
  		topics: [] 
	}],
	jsonrpc: "2.0",
	id: "2"
}, callback);
```

To work around the issue I use the following since it works:
```
var filter = web3.eth.filter({fromBlock:fromBlock,toBlock:toBlock,address:address});
filter.get(function(error,logs){
	filter.stopWatching();
	callback(error,logs);
});
```

## Context
I would like to skip the need to create filter and just use eth_getLogs

## Your Environment

* Version used: 3.10.10
* Operating System and version: Windows 10

**Comment by benjamincburns** [comment]
@wighawag I'm so sorry this went for so long without a response! I think this is no longer an issue, so I'm closing. However if I'm wrong on this, please don't hesitate to reopen.
