### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by miguelmota** [ConsenSys-archive/ganache-cli-archive#373]
randomly crashes with error

```bash
eth_sendRawTransaction
eth_sendRawTransaction
eth_sendRawTransaction
eth_sendRawTransaction
/Users/mota/.nvm/versions/node/v7.9.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:61262
    db.get(key, {
      ^

TypeError: Cannot read property 'get' of undefined
    at dbGet (/Users/mota/.nvm/versions/node/v7.9.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:61262:7)
    at /Users/mota/.nvm/versions/node/v7.9.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:17720:5
    at /Users/mota/.nvm/versions/node/v7.9.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:24532:20
    at iterate (/Users/mota/.nvm/versions/node/v7.9.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:24613:13)
    at /Users/mota/.nvm/versions/node/v7.9.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:24625:29
    at /Users/mota/.nvm/versions/node/v7.9.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:24395:16
    at /Users/mota/.nvm/versions/node/v7.9.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:17725:7
    at /Users/mota/.nvm/versions/node/v7.9.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:61267:9
    at dispatchError (/Users/mota/.nvm/versions/node/v7.9.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:31665:35)
    at /Users/mota/.nvm/versions/node/v7.9.0/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:23916:14
```

**Comment by miguelmota** [comment]
related https://github.com/ethereumjs/testrpc/issues/340

**Comment by benjamincburns** [comment]
@miguelmota so sorry it has taken us so long to respond to this! We're tracking this issue over on #417 now, so I'll close this one as a duplicate.
