### ISSUE TITLE
can't unlock accounts

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [ConsenSys-archive/ganache-cli-archive#375]
$ testrpc --secure --unlock
/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:82912
      address = accounts[parseInt(address)].address;
                                           ^

TypeError: Cannot read property 'address' of undefined
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:82912:44
    at Array.reduce (native)
    at StateManager.initialize (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:82908:62)
    at new GethApiDouble (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:82387:14)
    at new Provider (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:29561:23)
    at Object.create (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:98437:20)
    at Object.server (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:52047:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:43033:22)
    at __webpack_require__ (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:21:30)
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64:18

address = accounts[parseInt(address)].address;
accounts are empty here...

## Your Environment

* Version used:EthereumJS TestRPC v4.1.1 (ganache-core: 1.1.2)
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version: Linux vitaliy-desktop 4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by tcoulter** [comment]
Hi there. Please check out the [TestRPC documentation](https://github.com/ethereumjs/testrpc). You need to pass the address you want to unlock, e.g.,

```
testrpc --unlock <address> --unlock <another address>
```

Alternatively you can unlock an address at an index:

```
testrpc --unlock 0
```

Which will unlock the first default account.
