### ISSUE TITLE
Issue when forking

### ISSUE THREAD

**Issue by chevdor** [ConsenSys-archive/ganache-cli-archive#393]
```
$ testrpc -f http://127.0.0.1:8545  -p 8546  -a="0x40a09056c8bd28bfc7806b85d82dabd681b0b1f3,
d707f2ee4309b47cf50b96eb084db815a8034acfe3809ab4e9f69d33d5b6e9d8,42000000000000000000" -n -u 1
/Users/chevdor/.nvm/versions/node/v8.1.4/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:82899
  this.coinbase = to.hex(accounts[0].address);
                                    ^

TypeError: **Cannot read property 'address' of undefined**
    at StateManager.initialize (/Users/chevdor/.nvm/versions/node/v8.1.4/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:82899:37)
    at new GethApiDouble (/Users/chevdor/.nvm/versions/node/v8.1.4/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:82387:14)
    at new Provider (/Users/chevdor/.nvm/versions/node/v8.1.4/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:29561:23)
    at Object.create (/Users/chevdor/.nvm/versions/node/v8.1.4/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:98436:20)
    at Object.server (/Users/chevdor/.nvm/versions/node/v8.1.4/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:52047:19)
    at Object.<anonymous> (/Users/chevdor/.nvm/versions/node/v8.1.4/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:43033:22)
    at __webpack_require__ (/Users/chevdor/.nvm/versions/node/v8.1.4/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:21:30)
    at /Users/chevdor/.nvm/versions/node/v8.1.4/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64:18
    at Object.<anonymous> (/Users/chevdor/.nvm/versions/node/v8.1.4/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:67:10)
    at Module._compile (module.js:569:30)
```

## Expected Behavior
No error

## Current Behavior
Error

## Steps to Reproduce (for bugs)
1. testrpc &
2. testrpc -f http://127.0.0.1:8545  -p 8546  -a="0x40a09056c8bd28bfc7806b85d82dabd681b0b1f3,
d707f2ee4309b47cf50b96eb084db815a8034acfe3809ab4e9f69d33d5b6e9d8,42000000000000000000" -n -u 1

# Your Environment

* Version used: 4.1.3
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): node v8.1.4
* Operating System and version: OSX

**Comment by benjamincburns** [comment]
This was an easy repro - thanks for the report, @chevdor! So sorry it has taken this long to get back to you on this!

**Comment by benjamincburns** [comment]
@chevdor thanks for reporting this, and sorry it's taken me so long!

You have a few issues here.

1. You want `--account`, not `-a`. Until recently this was incorrect in our `README.md` file :-(.
2. Don't specify the the address as part of the argument, it'll be calculated for you from the private key
3. You need a leading `0x` in front of your private key
4. `-u 1` is incorrect, because you've only got one account, and accounts are zero-indexed. You want `-u 0`.

Our error messages really suck here. I intend to do a round on input validation for the CLI, which will help, and I've already made a small improvement as a result of this case in trufflesuite/ganache-core@a48a99d2.

I'll close this for now, as I intend to track the input validation case elsewhere.
