### ISSUE TITLE
callback is not a function 

### ISSUE THREAD

**Issue by kumavis** [ConsenSys-archive/ganache-cli-archive#40]
getting an error from testrpc 1.2.1

```
╭─kumavis@xyzs-MacBook-Pro  ~/dev/sxsw-demo   
╰─$ curl -d '{"jsonrpc":"2.0","method":"eth_getBalance","params": ["0xa28d9923203601efb12fe777a9ab934d489e45c5"], "id":1}' -X POST http://139.196.191.70:8545 | jsonogram
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1296    0  1188  100   108   2144    194 --:--:-- --:--:-- --:--:--  2144
├─ id: 1
├─ jsonrpc: 2.0
└─ error
   ├─ message: TypeError: callback is not a function
    at /usr/lib/node_modules/ethereumjs-testrpc/lib/blockchain.js:166:7
    at /usr/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/stateManager.js:63:5
    at Cache.getOrLoad (/usr/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/cache.js:75:5)
    at StateManager.proto.getAccount (/usr/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/stateManager.js:37:14)
    at StateManager.proto.getAccountBalance (/usr/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/stateManager.js:61:8)
    at Blockchain.getBalance (/usr/lib/node_modules/ethereumjs-testrpc/lib/blockchain.js:159:24)
    at Manager.eth_getBalance (/usr/lib/node_modules/ethereumjs-testrpc/lib/manager.js:96:19)
    at Manager.handleRequest (/usr/lib/node_modules/ethereumjs-testrpc/lib/manager.js:59:10)
    at next (/usr/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:93:18)
    at VmSubprovider.handleRequest (/usr/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/vm.js:42:12)
   └─ code: -32000
```

**Comment by tcoulter** [comment]
This does not appear to be a bug anymore, at least it doesn't when running it locally:

```
Tims-MacBook-Pro:provider-engine tim$ curl -d '{"jsonrpc":"2.0","method":"eth_getBalance","params": ["0x038edf71c17a123671b9ae86b5d202bf90a63d98"], "id":1}' -X POST http://localhost:8545
{"id":1,"jsonrpc":"2.0","result":"0x00000000000000056bc75e2d63100000"}
```

Closing. Reopen if this is still and issue.
