### ISSUE TITLE
Testrpc crash on advanceBlock call

### ISSUE THREAD

**Issue by k06a** [ConsenSys-archive/ganache-cli-archive#404]
## Expected Behavior
I have medium size truffle project with some tests. And working on increasing test coverage. Just added new tests file with simple new test and wanna it to pass or fail.

## Current Behavior
I see testrpc failure on `await advanceBlock()`:
```
evm_mine
evm_mine
evm_snapshot
Saved snapshot #1
TypeError: Cannot read property 'modified' of undefined
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:63964:18
    at Object.whilst (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:12674:5)
    at module.exports.Cache.flush (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:63961:9)
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:69191:31
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:17637:36
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:63236:9
    at item.task (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:62914:29)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

## Possible Solution
Commenting line `await advanceBlock()`

## Steps to Reproduce (for bugs)

1. Download sources from `bug/demo` branch: https://github.com/bitclave/crowdsale/tree/bug/demo
2. Run `testrpc` within script: `./scripts/run.sh`
3. Run tests: `truffle test`

## Context
I can't add this simple test to project

## Your Environment

* Version used: EthereumJS TestRPC v4.1.3 (ganache-core: 1.1.3)
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): 
* Server type and version: MacBook Pro Retina 15" Mid 2015
* Operating System and version: macOS 10.13
* Link to your project: https://github.com/bitclave/crowdsale/tree/bug/demo
* Truffle: Truffle v3.4.11 - a development framework for Ethereum
* NodeJS: NodeJS v8.7.0

**Comment by k06a** [comment]
Found reason:
```
contract('AnyContract1', async function ([_, wallet, wallet2, wallet3]) {
    await advanceBlock();
    // ...
})

contract('AnyContract2', async function ([_, wallet, wallet2, wallet3]) {
    await advanceBlock();
    // ...
})
```

Moved `await advanceBlock();` into `before` blocks
