### ISSUE TITLE
eth_call incorrect RPC return value

### ISSUE THREAD

**Issue by nunofmn** [ConsenSys-archive/ganache-cli-archive#41]
In `ethereumjs-testrpc@1.2.1` when using the `call` method (in this case using `ether-pudding`) the following error occurs:

```
Debug: internal, implementation, error
    BigNumber Error: Uncaught error: new BigNumber() not a base 16 number:
    at raise (/Users/nunofmn1/app/node_modules/bignumber.js/bignumber.js:1177:25)
    at /Users/nunofmn1/app/node_modules/bignumber.js/bignumber.js:1165:33
    at new BigNumber (/Users/nunofmn1/app/node_modules/bignumber.js/bignumber.js:212:28)
    at formatOutputString [as _outputFormatter] (/Users/nunofmn1/app/node_modules/web3/lib/solidity/formatters.js:217:19)
    at /Users/nunofmn1/app/node_modules/web3/lib/solidity/type.js:237:25
    at SolidityType.decode (/Users/nunofmn1/app/node_modules/web3/lib/solidity/type.js:238:11)
    at /Users/nunofmn1/appnode_modules/web3/lib/solidity/coder.js:219:29
    at Array.map (native)
    at SolidityCoder.decodeParams (/Users/nunofmn1/app/node_modules/web3/lib/solidity/coder.js:218:26)
    at SolidityFunction.unpackOutput (/Users/nunofmn1/app/node_modules/web3/lib/web3/function.js:90:24)
    at Object.callback (/Users/nunofmn1/app/node_modules/web3/lib/web3/function.js:118:30)
    at /Users/nunofmn1/Documents/app/node_modules/web3/lib/web3/method.js:142:25
    at /Users/nunofmn1/Documents/app/node_modules/web3/lib/web3/requestmanager.js:89:9
    at request.onreadystatechange (/Users/nunofmn1/app/node_modules/web3/lib/web3/httpprovider.js:114:13)
    at dispatchEvent (/Users/nunofmn1/app/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/Users/nunofmn1/app/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
```

With further debugging is possible to verify that the problem is in the `formatOutputString` function, and is related with the JSON returned by the `testrpc`client:

``` json
{
  id: 2,
  jsonrpc: "2.0",
  result: "0x"
}
```

Which seems related with https://github.com/ethereum/web3.js/issues/231.

**Comment by tcoulter** [comment]
Hi there, sorry for the late response.

Please submit code we can use to reproduce this issue. Otherwise we won't be able to debug it. I'm going to close it for housekeeping, but if you find the issue still persists please reopen. Thanks!

**Comment by Shadowstep33** [comment]
Any update on this? I may be hitting the same error @nunofmn (in web3)
