### ISSUE TITLE
block time crash the testrpc

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [ConsenSys-archive/ganache-cli-archive#421]
Hello, I tried to compare "now" with time in the "require" statement, as a result it crashes.
```
th_getTransactionReceipt

  Transaction: 0x06c639176830d17667c26c8d7d9ab978293688a0f08c929dff2d79c1f6a64be2
  Contract created: 0x081e7ea3b8a196bc56820b5b9cd1d1d9b1adacd8
  Gas usage: 269607
  Block Number: 8578
  Block Time: Thu Nov 09 2017 18:45:13 GMT+0200 (EET)

eth_getFilterChanges
eth_getFilterChanges
eth_getFilterChanges
eth_getFilterChanges
eth_getTransactionReceipt
eth_getCode
/home/v/.npm-global/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:68497
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRO

TypeError: Cannot read property 'get' of undefined
    at dbGet (/home/v/.npm-global/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:61930:8)
    at /home/v/.npm-global/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:17591:5
    at /home/v/.npm-global/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:23173:20
    at iterate (/home/v/.npm-global/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:23254:13)
    at /home/v/.npm-global/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:23266:29
    at /home/v/.npm-global/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:23036:16
    at /home/v/.npm-global/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:17596:7
    at /home/v/.npm-global/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:61935:9
    at dispatchError (/home/v/.npm-global/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:33055:36)
    at /home/v/.npm-global/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:22826:14

```

**Comment by benjamincburns** [comment]
@vitaliy-kuzmich thanks for reporting! Lets follow this issue over on #417.

**Comment by Silur** [comment]
@vitaliy-kuzmich are you using a docker setup?

**Comment by vitaliy-kuzmich** [comment]
@Silur no
