### ISSUE TITLE
-a/--accounts option not working

### ISSUE THREAD

**Issue by sudeep30m** [ConsenSys-archive/ganache-cli-archive#454]
I am using ganache-cli version 6.0.3. It gives an error when -a option is used.

On typing the command on MacOS 10.13 -

` ganache-cli -a 10
`

The following error is generated -
```
Ganache CLI v6.0.3 (ganache-core: 2.0.2)
/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:74142
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!

Error: listen EADDRINUSE :::8545
    at Object._errnoException (util.js:999:13)
    at _exceptionWithHostPort (util.js:1020:20)
    at Server.setupListenHandle [as _listen2] (net.js:1379:14)
    at listenInCluster (net.js:1420:12)
    at Server.listen (net.js:1508:7)
    at Server.server.listen (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:106029:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:50243:8)
    at __webpack_require__ (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:21:30)
    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:64:18
    at Object.<anonymous> (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:67:10)
```

**Comment by benjamincburns** [comment]
Thanks for closing this once you figured it out, @sudeep30m!

**Comment by Mirajjj** [comment]
@sudeep30m Could you please explain what you did to make any ganache-cli command work? I have the same issue but on Windows 8.
