### ISSUE TITLE
eth_blockNumber with param ["latest"] kills ganache-cli with TypeError: callback is not a function

### ISSUE THREAD

**Issue by vsdigitall** [ConsenSys-archive/ganache-cli-archive#456]
When I send the following request to ganache-cli:
```
{
  method: "eth_blockNumber", 
  params: ["latest"]
}
```
it throws:
```
C:\node\node_modules\ganache-cli\build\cli.node.js:74142
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRON

TypeError: callback is not a function
    at C:\node\node_modules\ganache-cli\build\cli.node.js:89905:5
    at C:\node\node_modules\ganache-cli\build\cli.node.js:22569:5
    at C:\node\node_modules\ganache-cli\build\cli.node.js:85331:5
    at C:\node\node_modules\ganache-cli\build\cli.node.js:85777:12
    at C:\node\node_modules\ganache-cli\build\cli.node.js:85542:19
    at C:\node\node_modules\ganache-cli\build\cli.node.js:87681:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

If I send this command (without "latest"):
```
{
  method: "eth_blockNumber", 
  params: []
}
```
Ganache-cli successfully process request and returns correct reply:
```
eth_blockNumber
   > {
   >   "jsonrpc": "2.0",
   >   "id": 4895,
   >   "method": "eth_blockNumber",
   >   "params": [],
   >   "external": true
   > }
 <   {
 <     "id": 4895,
 <     "jsonrpc": "2.0",
 <     "result": "0x03"
 <   }
```

**Comment by vsdigitall** [comment]
My fault, misundestood documentation. Closing this.
