### ISSUE TITLE
TypeError: Cannot read property 'modified' of undefined

### ISSUE THREAD

**Issue by k06a** [ConsenSys-archive/ganache-cli-archive#480]
Crash on transaction.

* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [x]
* Link to my question on gitter: https://gitter.im/ConsenSys/truffle?at=5a81fc9ce217167e2c766824

## Expected Behavior

Do no crash ganache-cli

## Current Behavior

Crash with following output:
```
/home/travis/build/MyEtherHODL/MyEtherHODL/node_modules/ganache-cli/build/cli.node.js:74142
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;E

TypeError: Cannot read property 'modified' of undefined
    at /home/travis/build/MyEtherHODL/MyEtherHODL/node_modules/ganache-cli/build/cli.node.js:72248:17
    at Object.whilst (/home/travis/build/MyEtherHODL/MyEtherHODL/node_modules/ganache-cli/build/cli.node.js:14777:5)
    at module.exports.Cache.flush (/home/travis/build/MyEtherHODL/MyEtherHODL/node_modules/ganache-cli/build/cli.node.js:72245:9)
    at /home/travis/build/MyEtherHODL/MyEtherHODL/node_modules/ganache-cli/build/cli.node.js:76342:31
    at /home/travis/build/MyEtherHODL/MyEtherHODL/node_modules/ganache-cli/build/cli.node.js:17596:36
    at /home/travis/build/MyEtherHODL/MyEtherHODL/node_modules/ganache-cli/build/cli.node.js:69521:9
    at item.task (/home/travis/build/MyEtherHODL/MyEtherHODL/node_modules/ganache-cli/build/cli.node.js:69199:29)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
Full here: https://travis-ci.org/MyEtherHODL/MyEtherHODL/builds/342224314

## Possible Solution

No solution

## Steps to Reproduce (for bugs)

You can repeat steps from Travis-CI config: `.travis.yml`

## Your Environment
* Version used: 6.0.3
* Version of Truffle/Remix/Other tools used: Truffle 4.0.6
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [x] 8.x, [ ] 9.x
* Operating System and version (include distro if Linux): Ubuntu
* Link to your project or repro gist: https://github.com/MyEtherHODL/MyEtherHODL
* Commit hash to use with above link for reproduction: 3b2585e3ccc2d19a5439dacfad2199a5ec143a88
* I intend to submit a pull request to fix this issue: [ ]

**Comment by mikeseese** [comment]
@benjamincburns says that one of the releases ~6.1.0+ made it to process requests serially, and that should fix this issue. If you still have problems, please open a new issue. Thanks!
