### ISSUE TITLE
ganache-cli crashes on calls to address "0x08"

### ISSUE THREAD

**Issue by tjade273** [ConsenSys-archive/ganache-cli-archive#492]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [ ]

## Expected Behavior

Address "0x08" should implement the EIP-197 bn_128 pairing check precompile. 

## Current Behavior
When sent a transaction of the form 
`eth.call({to:"0x0000000000000000000000000000000000000008", data:""})`
ganache crashes with
```
/home/tjaden/.node_modules/lib/node_modules/ganache-cli/build/cli.node.js:74142
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRO

TypeError: Cannot read property 'programCounter' of undefined
    at RuntimeError.combine (/home/tjaden/.node_modules/lib/node_modules/ganache-cli/build/cli.node.js:25258:47)
    at new RuntimeError (/home/tjaden/.node_modules/lib/node_modules/ganache-cli/build/cli.node.js:25229:8)
    at Function.RuntimeError.fromResults (/home/tjaden/.node_modules/lib/node_modules/ganache-cli/build/cli.node.js:25283:13)
    at /home/tjaden/.node_modules/lib/node_modules/ganache-cli/build/cli.node.js:22083:30
    at /home/tjaden/.node_modules/lib/node_modules/ganache-cli/build/cli.node.js:76465:5
    at /home/tjaden/.node_modules/lib/node_modules/ganache-cli/build/cli.node.js:13438:9
    at /home/tjaden/.node_modules/lib/node_modules/ganache-cli/build/cli.node.js:10037:16
    at replenish (/home/tjaden/.node_modules/lib/node_modules/ganache-cli/build/cli.node.js:10557:25)
    at iterateeCallback (/home/tjaden/.node_modules/lib/node_modules/ganache-cli/build/cli.node.js:10547:17)
    at /home/tjaden/.node_modules/lib/node_modules/ganache-cli/build/cli.node.js:10522:16
```

## Possible Solution
This seems like it may be an upstream problem with ethereumjs-util. I will investigate further and submit an upstream issue if this is the case.

## Steps to Reproduce (for bugs)
`web3.eth.call({to:"0x0000000000000000000000000000000000000008", data:""})`

## Context

Trying to develop applications using this precompile are impossible with this bug
## Your Environment
* Version used: Ganache CLI v6.0.3 (ganache-core: 2.0.2)
* Version of Truffle/Remix/Other tools used: web3@0.20.5
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [ ] 8.x, [x] 9.x
* Operating System and version (include distro if Linux): Arch Linux
* Link to your project or repro gist:
* Commit hash to use with above link for reproduction:
* I intend to submit a pull request to fix this issue: [ ]

**Comment by benjamincburns** [comment]
@tjade273 thanks for reporting this. I believe this is fixed in v6.1.0 which is out now.
