### ISSUE TITLE
VM error with a contract that deploys another contract

### ISSUE THREAD

**Issue by ericwooley** [ConsenSys-archive/ganache-cli-archive#496]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [x]
I talked to ngidian? in truffle at the end of feb about this before I went on vacation. So I can't find the log now.

## Expected Behavior
The test should complete with a rejection or tx result.

## Current Behavior
VM spits out error on method call

```
  ● AdFactory › methods › should deploy an ad

    c: VM Exception while processing transaction: revert
      
      at Function.c.fromResults (node_modules/ganache-cli/build/webpack:/ganache/node_modules/rustbn.js/index.js:3:1)
      at node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/lib/blockchain_double.js:548:1
      at node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/internal/eachOfLimit.js:3:1
      at l (node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/internal/eachOfLimit.js:16:1)
      at node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/internal/eachOfLimit.js:28:39
      at t.default (node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/eachLimit.js:20:1)
      at node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/internal/slice.js:3:1
      at g.n.emit (node_modules/ganache-cli/build/webpack:/ganache/node_modules/async-eventemitter/lib/AsyncEventEmitter.js:58:1)
      at node_modules/ganache-cli/build/webpack:/ganache/node_modules/ethereumjs-vm/lib sync:2:1
      at node_modules/ganache-cli/build/webpack:/ganache/node_modules/ethereumjs-vm/lib sync:2:1
      at node_modules/ganache-cli/build/webpack:/ganache/node_modules/ethereumjs-vm/lib/cache.js:117:1
      at node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:480:1
      at o (node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:1030:1)
      at node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:1032:1
      at Ut (node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:3245:1)
      at Object.<anonymous> (node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:1049:10)
      at node_modules/ganache-cli/build/webpack:/ganache/node_modules/ethereumjs-vm/lib/cache.js:113:1
      at node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:966:1
      at c (node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:5240:1)
      at node_modules/ganache-cli/build/webpack:/ganache/node_modules/ethereumjs-vm/lib/cache.js:107:1
      at c (node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:5239:1)
      at node_modules/ganache-cli/build/webpack:/ganache/node_modules/ethereumjs-vm/lib/cache.js:107:1
      at c (node_modules/ganache-cli/build/webpack:/ganache/node_modules/async/dist/async.js:5239:1)
      at node_modules/ganache-cli/build/webpack:/ganache/node_modules/ethereumjs-vm/lib/cache.js:105:1
      at node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/util.js:64:1
      at node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:37:1
      at f (node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:255:1)
      at node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:52:1
      at Immediate.<anonymous> (node_modules/ganache-cli/build/webpack:/ganache/node_modules/levelup/lib/levelup.js:290:1)
```

[Contract code](https://github.com/ericwooley/EtherAds/blob/e2ad40286947466f16b3cfa94e49e49125ef6415/packages/smart-contracts/src/AdFactory.sol#L25)

[Test Code](https://github.com/ericwooley/EtherAds/blob/e2ad40286947466f16b3cfa94e49e49125ef6415/packages/smart-contracts/src/AdFactory.test.ts#L68)

## Steps to Reproduce (for bugs)

1. `git clone git@github.com:ericwooley/EtherAds.git && cd EtherAds && git checkout e2ad40286947466f16b3cfa94e49e49125ef6415`
2. `yarn`
3. `yarn test`

## Context
Just blocking unit tests

## Your Environment
* Version used: ganache-cli@6.1.0
* Version of Truffle/Remix/Other tools used: web3@1.0.0.beta30
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [ ] 8.x, [x] 9.x
* Operating System and version (include distro if Linux): Ubuntu 16.04
* Link to your project or repro gist: https://github.com/ericwooley/EtherAds/blob/e2ad40286947466f16b3cfa94e49e49125ef6415/packages/smart-contracts
* Commit hash to use with above link for reproduction: e2ad40286947466f16b3cfa94e49e49125ef6415
* I intend to submit a pull request to fix this issue: [ ] If I can figure it out maybe

**Comment by olaf89** [comment]
I have the same issue

**Comment by mikeseese** [comment]
@ericwooley I'm guessing this is related to gas estimation as well. Like my other response, I'm going to close this issue in favor of https://github.com/trufflesuite/ganache-core/issues/26
