### ISSUE TITLE
syntax error: Unexpected Identifier

### ISSUE THREAD

**Issue by vidhyaramani** [ConsenSys-archive/ganache-cli-archive#516]
Same error am getting again and again. I have asked the same question on issue number: #910. I have followed the same procedure but still the error is there. Please help me to solve this. 

truffle(develop)> migrate--reset
evalmachine.<anonymous>:1
migrate--reset
         ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInContext (vm.js:181:10)
    at Console.interpret (C:\Users\labo\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:107145:17)
    at ReplManager.interpret (C:\Users\labo\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:107862:18)
    at bound (domain.js:375:14)
    at REPLServer.runBound [as eval] (domain.js:388:12)
    at REPLServer.onLine (repl.js:492:10)
    at REPLServer.emit (events.js:180:13)
    at REPLServer.emit (domain.js:421:20)

## Your Environment
* Version used: npm :5.8.0
* Version of Truffle/Remix/Other tools used: v4.1.7
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [ ] 8.x, [ ] 9.x v9.9.0
* Operating System and version (include distro if Linux): Windows
* Link to your project or repro gist:https://github.com/trufflesuite/truffle/issues/910#issuecomment-383961120. 
* Commit hash to use with above link for reproduction:
* I intend to submit a pull request to fix this issue: [ ]

**Comment by cgewecke** [comment]
`reset` is a command-line option. More info [here](http://truffleframework.com/docs/advanced/commands#migrate) at the truffle commands documentation.
```
migrate --reset
```
