### ISSUE TITLE
Use --unlock 0 get "TypeError: a.options.unlocked_accounts.reduce is not a function"

### ISSUE THREAD

**Issue by danny50610** [ConsenSys-archive/ganache-cli-archive#545]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [ ]

## Expected Behavior
```
>ganache-cli --secure --unlock 0
Ganache CLI v6.1.0 (ganache-core: 2.1.0)

Available Accounts
==================
(0) 0xb530e11134dbf0a5a8da1351b61e7fcde399f695
(1) 0xb458b7c40420c9e1d8a46e02e061c479feef8df7 🔒
(2) 0xe7cf6f98ece38961af85582e750c53f76d8c97d4 🔒
(3) 0x9afcf7c1df54eef14c491873ae3ec527b8322f95 🔒
(4) 0x5a8a73fbfb164bbc102a8156cef9fcb434966ed5 🔒
(5) 0x4a4f4240410efa7d6fa8fc88edbab369adead78a 🔒
(6) 0x4456e94ce3becd17ea25edbf7cb78f408d86d771 🔒
(7) 0x833b4fdbc1ae992c35f4c4c3633f7608e638c4ce 🔒
(8) 0x1e96da8863eb83d781edd78e368872cfa3e43906 🔒
(9) 0x0a81a2ef9021cd4cad4af1b788a41e71041a7431 🔒

Private Keys
==================
(0) 91b178d63afdbb70269794ca3126fcabe40f1df11a8d4b6c9ae2cea2b2f8b5fe
(1) d627b98286510d93ed3009f3fb398a46b88120619393516978de8bbeb5b8cc95
(2) a4c8693b6696c45b5b8db47b5fb2192f751400090f121a2f06b41d072cc9f162
(3) 421e6334bbef949bf74aa2a25af457dc09990ee132e0a79598bae70bd77f1809
(4) 399ec09d7eba513b10dcd1ce953a4f4163d297605c6d78ffb667db644728515f
(5) d785387ea90e490b1670bf05256e1ba7c4c298f16a4aecbbfd84b448b0b43425
(6) 2e74cbec18d50c2dbf33dac0f79cab113a4ec7866a947763930e24b27f08784a
(7) 6c8128884c14af03ba7885558a682c40ebde12a7d2693693e1ae804049a9f939
(8) 5cd74cc2970194a591fbf40f81bf8a653866d0a96efc998ffb63bc8b8a0b6d61
(9) 6fa0c9d3edf129d977feb42fd28dba48daebc1f8426392b23cc95e610963de05

HD Wallet
==================
Mnemonic:      cereal then pepper food excite chair yard dust essence rail notable style
Base HD Path:  m/44'/60'/0'/0/{account_index}

Listening on localhost:8545
```

## Current Behavior
```
>ganache-cli --secure --unlock 0

[skip a lot strange output, maybe is code]

TypeError: a.options.unlocked_accounts.reduce is not a function
    at StateManager.initialize (C:\Users\jyhsu\AppData\Roaming\npm\node_modules\ganache-cli\build\cli.node.js:2:3899391)
    at new s (C:\Users\jyhsu\AppData\Roaming\npm\node_modules\ganache-cli\build\cli.node.js:2:3910187)
    at new l (C:\Users\jyhsu\AppData\Roaming\npm\node_modules\ganache-cli\build\cli.node.js:2:653341)
    at Object.create (C:\Users\jyhsu\AppData\Roaming\npm\node_modules\ganache-cli\build\cli.node.js:2:707320)
    at Object.server (C:\Users\jyhsu\AppData\Roaming\npm\node_modules\ganache-cli\build\cli.node.js:2:4057119)
    at Object.<anonymous> (C:\Users\jyhsu\AppData\Roaming\npm\node_modules\ganache-cli\build\cli.node.js:2:4149061)
    at t (C:\Users\jyhsu\AppData\Roaming\npm\node_modules\ganache-cli\build\cli.node.js:2:110)
    at C:\Users\jyhsu\AppData\Roaming\npm\node_modules\ganache-cli\build\cli.node.js:2:524
    at Object.<anonymous> (C:\Users\jyhsu\AppData\Roaming\npm\node_modules\ganache-cli\build\cli.node.js:2:536)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)
```

## Your Environment
* Version used: 6.1.4
* NodeJS Version: [x] 8.x, [ ] 9.x, [x] 10.x 
* Operating System and version (include distro if Linux): Windows 10 1803 64bit

**Comment by mikeseese** [comment]
This will go in the next release. Thanks for reporting!
