### ISSUE TITLE
please improve install instructions for ubuntu user

### ISSUE THREAD

**Issue by mowliv** [ConsenSys-archive/ganache-cli-archive#57]
Tried to install using `sudo npm install -g ethereumjs-testrpc` (after first installing npm on ubuntu), and it failed with below errors. Please advise - thanks.

> secp256k1@3.0.1 rebuild /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-util/node_modules/secp256k1
> node-gyp rebuild

npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/elliptic
npm http 304 https://registry.npmjs.org/bn.js
npm http 304 https://registry.npmjs.org/drbg.js
npm http 304 https://registry.npmjs.org/nan
/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.2.0-34-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-util/node_modules/secp256k1
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-wallet/node_modules/secp256k1/node_modules/nan'
npm ERR! error rolling back  ethereumjs-testrpc@2.0.0 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-wallet/node_modules/secp256k1/node_modules/nan']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-wallet/node_modules/secp256k1/node_modules/nan' }
npm ERR! weird error 1
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-wallet/node_modules/secp256k1/node_modules/elliptic/lib/elliptic/curve/edwards.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 4.2.0-34-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "ethereumjs-testrpc"
npm ERR! cwd /home/michael
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-wallet/node_modules/secp256k1/node_modules/elliptic/lib/elliptic/curve/edwards.js
npm ERR! fstream_path /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-wallet/node_modules/secp256k1/node_modules/elliptic/lib/elliptic/curve/edwards.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-wallet/node_modules/secp256k1/node_modules/bn.js/lib/bn.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 4.2.0-34-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "ethereumjs-testrpc"
npm ERR! cwd /home/michael
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-wallet/node_modules/secp256k1/node_modules/bn.js/lib/bn.js
npm ERR! fstream_path /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-wallet/node_modules/secp256k1/node_modules/bn.js/lib/bn.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-wallet/node_modules/aes-js/~/.grip/style-cache/github2-27099ff875724b3da49fac6911968f783aa96ed08970c77185d963ce6c21af75.css'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 4.2.0-34-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "ethereumjs-testrpc"
npm ERR! cwd /home/michael
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-wallet/node_modules/aes-js/~/.grip/style-cache/github2-27099ff875724b3da49fac6911968f783aa96ed08970c77185d963ce6c21af75.css
npm ERR! fstream_path /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-wallet/node_modules/aes-js/~/.grip/style-cache/github2-27099ff875724b3da49fac6911968f783aa96ed08970c77185d963ce6c21af75.css
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! tar pack Error reading /home/michael/tmp/npm-8718-BCqEhiQ4/1459746703831-0.9252500941511244/package
npm ERR! addLocalDirectory Could not pack "/home/michael/tmp/npm-8718-BCqEhiQ4/1459746703831-0.9252500941511244/package" to "/home/michael/.npm/sha3/1.2.0/package.tgz"
npm http GET https://registry.npmjs.org/pbkdf2

> scrypt@6.0.1 preinstall /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-wallet/node_modules/scrypt.js/node_modules/scrypt
> node node-scrypt-preinstall.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm http 304 https://registry.npmjs.org/pbkdf2
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/michael/npm-debug.log
npm ERR! not ok code 0

**Comment by mowliv** [comment]
Figured this out. Followed your step to install via npm, and when that failed because I didn't have npm I installed it with `apt-get install npm` -- which got me an old setup. Worked for me and probably better for ubuntu users to follow these steps to install testrpc:

https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

Please update install instructions.
