### ISSUE TITLE
Error: the tx doesn't have the correct nonce. account has nonce of: 2 tx has nonce of: 1

### ISSUE THREAD

**Issue by MrChico** [ConsenSys-archive/ganache-cli-archive#6]
I'm doing some experiments with lists and ran in to an error with js testrpc that does not happen when using geth.
Using the following contract:

``` javascript
contract haslist {
    address[] public List;
    uint256 public size = 0;
    function addElement(address element) {
        List[size]=element;
        size++;
    }
}
```

I call the function addElement through rpc with:

```
> listhandle = haslistContract.at("0x4875ec1a939f7518e8ec707e261806c4fd233b3a");
> web3.eth.defaultAccount = web3.eth.accounts[0];
'0x269c8f830dbb1fbf59d9a354b7f9f353ae4c3f58'
> listhandle.addElement('0x4875ec1a939f7518e8ec707e261806c4fd233b3a');
Error: VM Exception while executing transaction: invalid JUMP
    at Object.module.exports.InvalidResponse (/home/martin/node_modules/web3/lib/web3/errors.js:35:16)
    at RequestManager.send (/home/martin/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Eth.send [as sendTransaction] (/home/martin/node_modules/web3/lib/web3/method.js:145:58)
    at SolidityFunction.sendTransaction (/home/martin/node_modules/web3/lib/web3/function.js:133:26)
    at SolidityFunction.execute (/home/martin/node_modules/web3/lib/web3/function.js:219:37)
    at repl:1:12
    at REPLServer.defaultEval (repl.js:164:27)
    at bound (domain.js:250:14)
    at REPLServer.runBound [as eval] (domain.js:263:12)
    at REPLServer.<anonymous> (repl.js:393:12)
> listhandle.addElement('0x4875ec1a939f7518e8ec707e261806c4fd233b3a');
Error: the tx doesn't have the correct nonce. account has nonce of: 3 tx has nonce of: 2
    at Object.module.exports.InvalidResponse (/home/martin/node_modules/web3/lib/web3/errors.js:35:16)
    at RequestManager.send (/home/martin/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Eth.send [as sendTransaction] (/home/martin/node_modules/web3/lib/web3/method.js:145:58)
    at SolidityFunction.sendTransaction (/home/martin/node_modules/web3/lib/web3/function.js:133:26)
    at SolidityFunction.execute (/home/martin/node_modules/web3/lib/web3/function.js:219:37)
    at repl:1:12
    at REPLServer.defaultEval (repl.js:164:27)
    at bound (domain.js:250:14)
    at REPLServer.runBound [as eval] (domain.js:263:12)
    at REPLServer.<anonymous> (repl.js:393:12)
```

**Comment by MrChico** [comment]
The problem is that the contract causes the VM to throw an error, and then calling the function again creates a transaction with the same nonce. Rather, one should use List.push(element). My bad
