### ISSUE TITLE
Facing trouble while testing in mocha using ganache-cli@6.2.5

### ISSUE THREAD

**Issue by akashde93** [ConsenSys-archive/ganache-cli-archive#612]
PS C:\Users\Akash\chat> npm run test

> chat@1.0.0 test C:\Users\Akash\chat
> mocha

C:\Users\Akash\chat\test\inbox.test.js:4
const web3=new Web3(ganache.provider());
                    ^
ReferenceError: ganache is not defined
    at Object.<anonymous> (C:\Users\Akash\chat\test\inbox.test.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at C:\Users\Akash\chat\node_modules\mocha\lib\mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\Akash\chat\node_modules\mocha\lib\mocha.js:247:14)
    at Mocha.run (C:\Users\Akash\chat\node_modules\mocha\lib\mocha.js:576:10)
    at Object.<anonymous> (C:\Users\Akash\chat\node_modules\mocha\bin\_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chat@1.0.0 test: `mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chat@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Akash\AppData\Roaming\npm-cache\_logs\2018-12-29T17_50_03_928Z-debug.log
PS C:\Users\Akash\chat>

**Comment by davidmurdoch** [comment]
What are the contents of C:\Users\Akash\chat\test\inbox.test.js?

**Comment by akashde93** [comment]
> What are the contents of C:\Users\Akash\chat\test\inbox.test.js?



> What are the contents of C:\Users\Akash\chat\test\inbox.test.js?

Hello David.. I have checked the Inbox.test.js and there was some typing errors and now its running properly. Thank You for replying to me.

**Comment by nicholasjpaterno** [comment]
@akashde93 that's great news!  I'm going to close this issue for now, please feel free to reopen if you run into similar issues.
