### ISSUE TITLE
ganache-cli error

### ISSUE THREAD

**Issue by pkrasam** [ConsenSys-archive/ganache-cli-archive#620]
getting this error for command: ganache-cli

module.js:550
    throw err;
    ^

Error: Cannot find module 'buffer-from'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ganache-cli/node_modules/source-map-support/source-map-support.js:15:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by davidmurdoch** [comment]
Thanks @pkrasam for taking the time to open this issue! What version of `ganache-cli` are you installing and what OS are you running on?

**Comment by pkrasam** [comment]
Mac OS
The latest version of ganache-cli

**Comment by davidmurdoch** [comment]
Thanks for following up, @pkrasam! We've had couple of releases since you've opened the issue. Can you try running `npm install ganache-cli@latest -g` and let me know it works for you now? If it still does not work, can you let me know what version of Mac OS, npm, and node.js you are running?

**Comment by sumreenali** [comment]
I facing this idssue when I add truffle-config file in ganache and it just throw me this error

An error occurred while running D:\Blockchain-Marketplace-App-Using-Ehereum-Web3-Solidity-and-React\truffle-config.js! Did you forget to `npm install` your project?

module.js:550
    throw err;
    ^

Error: Cannot find module 'C:\Users\Munir\AppData\Local\Temp\ganache12004-5132-w9804b.3q2qe\index.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
