### ISSUE TITLE
Error: Returned error: sender account not recognized 

### ISSUE THREAD

**Issue by isaacsultan** [ConsenSys-archive/ganache-cli-archive#625]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [x]
* Link to my question on gitter: <https://gitter.im/ConsenSys/truffle?at=5c65651c80df6804a1a2e8fb>

## Expected Behavior

Using accounts provided by ganache-cli, I do not expect there to be any error.
Strange, because using the same account earlier in the test suite, in similar way `{from: user}` with no issue at all.

## Current Behavior

```
Error: Returned error: sender account not recognized

     at Object.ErrorResponse (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/web3-eth/~/web3-core-helpers/src/errors.js:29:1)
      at /Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/web3-eth/~/web3-core-requestmanager/src/index.js:140:1
      at /Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:112:1
      at XMLHttpRequest.request.onreadystatechange (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/web3/~/web3-providers-http/src/index.js:96:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest._setReadyState (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest._onHttpResponseEnd (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:318:1)
      at IncomingMessage.<anonymous> (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:289:47)
      at endReadableNT (_stream_readable.js:1094:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

## Steps to Reproduce (for bugs)

Error: Returned error: sender account not recognized 

* `ganache-cli`
* `truffle test ./test/ExampleContract.test.js`

```
contract("ExampleContract",  function([_, user]) {
   ...
   describe("exampleFunction", function () {
      it("should pass", async function () {
         contract.exampleFunction({from: user}); //ERROR
      });
   });
});
```

## Your Environment
* Version used: ganache-cli 6.3.0
* Version of Truffle/Remix/Other tools used: truffle v5.0.4
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [ ] 8.x, [ ] 9.x [x] 10.x
* Operating System and version (include distro if Linux): v10.14.2
* I intend to submit a pull request to fix this issue: [ ]

**Comment by cbruguera** [comment]
Why was this closed? Was the problem fixed?... I'm having the same error, still not finding a solution.

**Comment by SirPhemmiey** [comment]
This happens because you're trying to send a transaction from an address which the node(or ganache) does not know the private key of.

**Comment by ZeeshanAhmadKhalil** [comment]
@SirPhemmiey  how we can add another account in ganache using web3 ?

**Comment by SirPhemmiey** [comment]
@ZeeshanAhmadKhalil  Something like, `--account=<PRIVATE_KEY>, <BALANCE>`
 
`ganache-cli --account "0x70f1384b24df3d2cdaca7974552ec28f055812ca5e4da7a0ccd0ac0f8a4a9b00,9000000000000000000000"`

**Comment by cbruguera** [comment]
In the I figured out that I was generating only 10 accounts upon running ganache and was using accounts[10] from web3. It was fixed by running ganache with `ganache-cli -a 11`
