### ISSUE TITLE
2.0.1 broken

### ISSUE THREAD

**Issue by austing** [ConsenSys-archive/ganache-cli-archive#64]
See the following tracebacks. Probably comes from recent merge from eth-lightwallet. Downgrading to 2.0.0 fixes the issue.

```
Austins-MBP:MountainOfMoney Gross$ testrpc
/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/eth-lightwallet/node_modules/tweetnacl/nacl-fast.js:2152
       throw new TypeError('unexpected type ' + t + ', use Uint8Array');
             ^
TypeError: unexpected type [object Object], use Uint8Array
    at checkArrayTypes (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/eth-lightwallet/node_modules/tweetnacl/nacl-fast.js:2152:14)
    at Object.nacl.secretbox (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/eth-lightwallet/node_modules/tweetnacl/nacl-fast.js:2201:3)
    at Function.KeyStore._encryptString (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/eth-lightwallet/lib/keystore.js:113:21)
    at new KeyStore (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/eth-lightwallet/lib/keystore.js:91:29)
    at new Blockchain (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/blockchain.js:45:19)
    at new Manager (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/manager.js:14:21)
    at Object.Server.provider (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/server.js:153:19)
    at Object.Server.server (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/server.js:23:25)
    at Object.TestRPC.server (/usr/local/lib/node_modules/ethereumjs-testrpc/index.js:23:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/ethereumjs-testrpc/bin/testrpc:42:22)
```

```
Austins-MBP:ethereumjs-testrpc Gross$ npm test

> ethereumjs-testrpc@2.0.2 test /usr/local/lib/node_modules/ethereumjs-testrpc
> mocha ./test/**/*.js

/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/eth-lightwallet/node_modules/tweetnacl/nacl-fast.js:2152
       throw new TypeError('unexpected type ' + t + ', use Uint8Array');
             ^
TypeError: unexpected type [object Object], use Uint8Array
    at checkArrayTypes (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/eth-lightwallet/node_modules/tweetnacl/nacl-fast.js:2152:14)
    at Object.nacl.secretbox (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/eth-lightwallet/node_modules/tweetnacl/nacl-fast.js:2201:3)
    at Function.KeyStore._encryptString (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/eth-lightwallet/lib/keystore.js:113:21)
    at new KeyStore (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/eth-lightwallet/lib/keystore.js:91:29)
    at new Blockchain (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/blockchain.js:45:19)
    at new Manager (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/manager.js:14:21)
    at Object.Server.provider (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/server.js:153:19)
    at Object.TestRPC.provider (/usr/local/lib/node_modules/ethereumjs-testrpc/index.js:27:28)
    at Suite.<anonymous> (/usr/local/lib/node_modules/ethereumjs-testrpc/test/requests.js:507:28)
    at context.describe.context.context (/usr/local/lib/node_modules/mocha/lib/interfaces/bdd.js:47:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/ethereumjs-testrpc/test/requests.js:505:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /usr/local/lib/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/local/lib/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/usr/local/lib/node_modules/mocha/lib/mocha.js:468:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Test failed.  See above for more details.
```

**Comment by tcoulter** [comment]
Hi there. Can you tell me which version of Node you're using?

**Comment by austing** [comment]
Hi!
My npm is version 2.12.1
Thanks
Austin

**Comment by tcoulter** [comment]
Can you tell me your node version?

`node --version`

**Comment by austing** [comment]
Sorry -- v0.12.6

**Comment by tcoulter** [comment]
Can you try upgrading to Node 5.0?

**Comment by austing** [comment]
That fixes it.

**Comment by tcoulter** [comment]
Great to know, thanks! Will close. Let me know if you run into anymore issues.
