### ISSUE TITLE
Installation issues for ganache cli and Truffle on Mac OS Catalina  (version 10.15)

### ISSUE THREAD

**Issue by BTT21000** [ConsenSys-archive/ganache-cli-archive#687]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [ ]

## Expected Behavior

Being able to install ganache cli and truffle as expected and run ganache -cli and truffle from the Mac terminal using the commands below:

$ ganache cli
$ truffle

## Current Behavior

When trying to install ganache cli and truffle, the errors pasted below appear and it is not possible to start ganache cli.

## Possible Solution

I have checked this forum thread which has a similar error message as I do:
https://github.com/aragon/aragon-cli/issues/328

Hence as recommended I looked at this solution:
https://github.com/nodejs/node-gyp/wiki/Updating-npm%27s-bundled-node-gyp

so I have tried this
:~ me$ npm explore npm -g -- npm install node-gyp@latest

But it did not help.

## Steps to Reproduce (for bugs)

1. Upgrade Mac from OS Mojave to OS Catalina

1. Manual Installation of Node.js 10.16.3 LTS for Mac OS from https://nodejs.org

2.$ npm -v
6.12.0

3.$ node -v
v12.13.0

4.

:~ me$ npm install truffle

> truffle@5.0.41 postinstall /Users/me/node_modules/truffle
> node ./scripts/postinstall.js

- Fetching solc version list from solc-bin. Attempt #1
npm WARN saveError ENOENT: no such file or directory, open '/Users/me/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/me/package.json'
npm WARN me No description
npm WARN me No repository field.
npm WARN me No README data
npm WARN me No license field.

+ truffle@5.0.41
added 27 packages from 439 contributors and audited 272 packages in 9.243s
found 0 vulnerabilities

:~ me$ truffle
-bash: truffle: command not found
:~ me$ npm uninstall -g ganache-cli && npm install -g ganache-cli
removed 88 packages in 0.645s
/Users/me/.npm-global/bin/ganache-cli -> /Users/me/.npm-global/lib/node_modules/ganache-cli/cli.js

> keccak@1.4.0 install /Users/me/.npm-global/lib/node_modules/ganache-cli/node_modules/keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."

> keccak@1.4.0 rebuild /Users/me/.npm-global/lib/node_modules/ganache-cli/node_modules/keccak
> node-gyp rebuild

  CXX(target) Release/obj.target/keccak/src/addon.o
../src/addon.cc:37:47: error: too few arguments to function call, single argument 'context' was
      not specified
    unsigned int rate = info[0]->IntegerValue();
                        ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/me/Library/Caches/node-gyp/12.13.0/include/node/v8.h:2609:3: note: 
      'IntegerValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
  ^
/Users/me/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:351:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/addon.cc:38:51: error: too few arguments to function call, single argument 'context' was
      not specified
    unsigned int capacity = info[1]->IntegerValue();
                            ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/me/Library/Caches/node-gyp/12.13.0/include/node/v8.h:2609:3: note: 
      'IntegerValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
  ^
/Users/me/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:351:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/addon.cc:56:48: error: too few arguments to function call, single argument 'context' was
      not specified
    unsigned char bits = info[0]->IntegerValue();
                         ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/me/Library/Caches/node-gyp/12.13.0/include/node/v8.h:2609:3: note: 
      'IntegerValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
  ^
/Users/me/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:351:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/addon.cc:64:43: error: too few arguments to function call, single argument 'context' was
      not specified
    size_t length = info[0]->IntegerValue();
                    ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/me/Library/Caches/node-gyp/12.13.0/include/node/v8.h:2609:3: note: 
      'IntegerValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
  ^
/Users/me/Library/Caches/node-gyp/12.13.0/include/node/v8config.h:351:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/addon.cc:75:73: error: no matching member function for call to 'ToObject'
    KeccakWrapper* to = Nan::ObjectWrap::Unwrap<KeccakWrapper>(info[0]->ToObject());
                                                               ~~~~~~~~~^~~~~~~~
/Users/me/Library/Caches/node-gyp/12.13.0/include/node/v8.h:2576:44: note: 
      candidate function not viable: requires single argument 'context', but no arguments were
      provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/me/Library/Caches/node-gyp/12.13.0/include/node/v8.h:2590:31: note: 
      candidate function not viable: requires single argument 'isolate', but no arguments were
      provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
5 errors generated.
make: *** [Release/obj.target/keccak/src/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/me/.npm-global/lib/node_modules/ganache-cli/node_modules/keccak
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2019-10-24T10_35_53_631Z-debug.log
Keccak bindings compilation fail. Pure JS implementation will be used.

> secp256k1@3.7.1 install /Users/me/.npm-global/lib/node_modules/ganache-cli/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."


> secp256k1@3.7.1 rebuild /Users/me/.npm-global/lib/node_modules/ganache-cli/node_modules/secp256k1
> node-gyp rebuild

  CXX(target) Release/obj.target/secp256k1/src/addon.o
  CXX(target) Release/obj.target/secp256k1/src/privatekey.o
../src/privatekey.cc:73:3: warning: ignoring return value of function declared with
      'warn_unused_result' attribute [-Wunused-result]
  secp256k1_ec_privkey_negate(secp256k1ctx, &private_key[0]);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/privatekey.cc:4:
In file included from ../src/secp256k1-src/src/scalar_impl.h:10:
In file included from ../src/secp256k1-src/src/group.h:11:
../src/secp256k1-src/src/field.h:36:13: warning: unused function 'secp256k1_fe_normalize'
      [-Wunused-function]
static void secp256k1_fe_normalize(secp256k1_fe *r);
            ^
../src/secp256k1-src/src/field.h:39:13: warning: unused function 'secp256k1_fe_normalize_weak'
      [-Wunused-function]
static void secp256k1_fe_normalize_weak(secp256k1_fe *r);
            ^
../src/secp256k1-src/src/field.h:42:13: warning: unused function 'secp256k1_fe_normalize_var'
      [-Wunused-function]
static void secp256k1_fe_normalize_var(secp256k1_fe *r);
            ^
../src/secp256k1-src/src/field.h:46:12: warning: unused function
      'secp256k1_fe_normalizes_to_zero' [-Wunused-function]
static int secp256k1_fe_normalizes_to_zero(secp256k1_fe *r);
           ^
../src/secp256k1-src/src/field.h:50:12: warning: unused function
      'secp256k1_fe_normalizes_to_zero_var' [-Wunused-function]
static int secp256k1_fe_normalizes_to_zero_var(secp256k1_fe *r);
           ^
../src/secp256k1-src/src/field.h:53:13: warning: unused function 'secp256k1_fe_set_int'
      [-Wunused-function]
static void secp256k1_fe_set_int(secp256k1_fe *r, int a);
            ^
../src/secp256k1-src/src/field.h:56:13: warning: unused function 'secp256k1_fe_clear'
      [-Wunused-function]
static void secp256k1_fe_clear(secp256k1_fe *a);
            ^
../src/secp256k1-src/src/field.h:59:12: warning: unused function 'secp256k1_fe_is_zero'
      [-Wunused-function]
static int secp256k1_fe_is_zero(const secp256k1_fe *a);
           ^
../src/secp256k1-src/src/field.h:62:12: warning: unused function 'secp256k1_fe_is_odd'
      [-Wunused-function]
static int secp256k1_fe_is_odd(const secp256k1_fe *a);
           ^
../src/secp256k1-src/src/field.h:65:12: warning: unused function 'secp256k1_fe_equal'
      [-Wunused-function]
static int secp256k1_fe_equal(const secp256k1_fe *a, const secp256k1_fe *b);
           ^
../src/secp256k1-src/src/field.h:68:12: warning: unused function 'secp256k1_fe_equal_var'
      [-Wunused-function]
static int secp256k1_fe_equal_var(const secp256k1_fe *a, const secp256k1_fe *b);
           ^
../src/secp256k1-src/src/field.h:71:12: warning: unused function 'secp256k1_fe_cmp_var'
      [-Wunused-function]
static int secp256k1_fe_cmp_var(const secp256k1_fe *a, const secp256k1_fe *b);
           ^
../src/secp256k1-src/src/field.h:74:12: warning: unused function 'secp256k1_fe_set_b32'
      [-Wunused-function]
static int secp256k1_fe_set_b32(secp256k1_fe *r, const unsigned char *a);
           ^
../src/secp256k1-src/src/field.h:77:13: warning: unused function 'secp256k1_fe_get_b32'
      [-Wunused-function]
static void secp256k1_fe_get_b32(unsigned char *r, const secp256k1_fe *a);
            ^
../src/secp256k1-src/src/field.h:81:13: warning: unused function 'secp256k1_fe_negate'
      [-Wunused-function]
static void secp256k1_fe_negate(secp256k1_fe *r, const secp256k1_fe *a, int m);
            ^
../src/secp256k1-src/src/field.h:85:13: warning: unused function 'secp256k1_fe_mul_int'
      [-Wunused-function]
static void secp256k1_fe_mul_int(secp256k1_fe *r, int a);
            ^
../src/secp256k1-src/src/field.h:88:13: warning: unused function 'secp256k1_fe_add'
      [-Wunused-function]
static void secp256k1_fe_add(secp256k1_fe *r, const secp256k1_fe *a);
            ^
../src/secp256k1-src/src/field.h:92:13: warning: unused function 'secp256k1_fe_mul'
      [-Wunused-function]
static void secp256k1_fe_mul(secp256k1_fe *r, const secp256k1_fe *a, const secp256k1_fe ...
            ^
../src/secp256k1-src/src/field.h:96:13: warning: unused function 'secp256k1_fe_sqr'
      [-Wunused-function]
static void secp256k1_fe_sqr(secp256k1_fe *r, const secp256k1_fe *a);
            ^
../src/secp256k1-src/src/field.h:103:12: warning: unused function 'secp256k1_fe_sqrt'
      [-Wunused-function]
static int secp256k1_fe_sqrt(secp256k1_fe *r, const secp256k1_fe *a);
           ^
../src/secp256k1-src/src/field.h:106:12: warning: unused function 'secp256k1_fe_is_quad_var'
      [-Wunused-function]
static int secp256k1_fe_is_quad_var(const secp256k1_fe *a);
           ^
../src/secp256k1-src/src/field.h:110:13: warning: unused function 'secp256k1_fe_inv'
      [-Wunused-function]
static void secp256k1_fe_inv(secp256k1_fe *r, const secp256k1_fe *a);
            ^
../src/secp256k1-src/src/field.h:113:13: warning: unused function 'secp256k1_fe_inv_var'
      [-Wunused-function]
static void secp256k1_fe_inv_var(secp256k1_fe *r, const secp256k1_fe *a);
            ^
../src/secp256k1-src/src/field.h:118:13: warning: unused function 'secp256k1_fe_inv_all_var'
      [-Wunused-function]
static void secp256k1_fe_inv_all_var(secp256k1_fe *r, const secp256k1_fe *a, size_t len);
            ^
../src/secp256k1-src/src/field.h:121:13: warning: unused function 'secp256k1_fe_to_storage'
      [-Wunused-function]
static void secp256k1_fe_to_storage(secp256k1_fe_storage *r, const secp256k1_fe *a);
            ^
../src/secp256k1-src/src/field.h:124:13: warning: unused function 'secp256k1_fe_from_storage'
      [-Wunused-function]
static void secp256k1_fe_from_storage(secp256k1_fe *r, const secp256k1_fe_storage *a);
            ^
../src/secp256k1-src/src/field.h:127:13: warning: unused function 'secp256k1_fe_storage_cmov'
      [-Wunused-function]
static void secp256k1_fe_storage_cmov(secp256k1_fe_storage *r, const secp256k1_fe_storag...
            ^
../src/secp256k1-src/src/field.h:130:13: warning: unused function 'secp256k1_fe_cmov'
      [-Wunused-function]
static void secp256k1_fe_cmov(secp256k1_fe *r, const secp256k1_fe *a, int flag);
            ^
In file included from ../src/privatekey.cc:4:
In file included from ../src/secp256k1-src/src/scalar_impl.h:10:
../src/secp256k1-src/src/group.h:44:13: warning: unused function 'secp256k1_ge_set_xy'
      [-Wunused-function]
static void secp256k1_ge_set_xy(secp256k1_ge *r, const secp256k1_fe *x, const secp256k1_fe *y);
            ^
../src/secp256k1-src/src/group.h:50:12: warning: unused function 'secp256k1_ge_set_xquad'
      [-Wunused-function]
static int secp256k1_ge_set_xquad(secp256k1_ge *r, const secp256k1_fe *x);
           ^
../src/secp256k1-src/src/group.h:54:12: warning: unused function 'secp256k1_ge_set_xo_var'
      [-Wunused-function]
static int secp256k1_ge_set_xo_var(secp256k1_ge *r, const secp256k1_fe *x, int odd);
           ^
../src/secp256k1-src/src/group.h:57:12: warning: unused function 'secp256k1_ge_is_infinity'
      [-Wunused-function]
static int secp256k1_ge_is_infinity(const secp256k1_ge *a);
           ^
../src/secp256k1-src/src/group.h:60:12: warning: unused function 'secp256k1_ge_is_valid_var'
      [-Wunused-function]
static int secp256k1_ge_is_valid_var(const secp256k1_ge *a);
           ^
../src/secp256k1-src/src/group.h:62:13: warning: unused function 'secp256k1_ge_neg'
      [-Wunused-function]
static void secp256k1_ge_neg(secp256k1_ge *r, const secp256k1_ge *a);
            ^
../src/secp256k1-src/src/group.h:65:13: warning: unused function 'secp256k1_ge_set_gej'
      [-Wunused-function]
static void secp256k1_ge_set_gej(secp256k1_ge *r, secp256k1_gej *a);
            ^
../src/secp256k1-src/src/group.h:68:13: warning: unused function 'secp256k1_ge_set_all_gej_var'
      [-Wunused-function]
static void secp256k1_ge_set_all_gej_var(secp256k1_ge *r, const secp256k1_gej *a, size_t len);
            ^
../src/secp256k1-src/src/group.h:75:13: warning: unused function
      'secp256k1_ge_globalz_set_table_gej' [-Wunused-function]
static void secp256k1_ge_globalz_set_table_gej(size_t len, secp256k1_ge *r, secp256k1_fe ...
            ^
../src/secp256k1-src/src/group.h:78:13: warning: unused function 'secp256k1_ge_set_infinity'
      [-Wunused-function]
static void secp256k1_ge_set_infinity(secp256k1_ge *r);
            ^
../src/secp256k1-src/src/group.h:81:13: warning: unused function 'secp256k1_gej_set_infinity'
      [-Wunused-function]
static void secp256k1_gej_set_infinity(secp256k1_gej *r);
            ^
../src/secp256k1-src/src/group.h:84:13: warning: unused function 'secp256k1_gej_set_ge'
      [-Wunused-function]
static void secp256k1_gej_set_ge(secp256k1_gej *r, const secp256k1_ge *a);
            ^
../src/secp256k1-src/src/group.h:87:12: warning: unused function 'secp256k1_gej_eq_x_var'
      [-Wunused-function]
static int secp256k1_gej_eq_x_var(const secp256k1_fe *x, const secp256k1_gej *a);
           ^
../src/secp256k1-src/src/group.h:90:13: warning: unused function 'secp256k1_gej_neg'
      [-Wunused-function]
static void secp256k1_gej_neg(secp256k1_gej *r, const secp256k1_gej *a);
            ^
../src/secp256k1-src/src/group.h:93:12: warning: unused function 'secp256k1_gej_is_infinity'
      [-Wunused-function]
static int secp256k1_gej_is_infinity(const secp256k1_gej *a);
           ^
../src/secp256k1-src/src/group.h:96:12: warning: unused function 'secp256k1_gej_has_quad_y_var'
      [-Wunused-function]
static int secp256k1_gej_has_quad_y_var(const secp256k1_gej *a);
           ^
../src/secp256k1-src/src/group.h:100:13: warning: unused function 'secp256k1_gej_double_nonzero'
      [-Wunused-function]
static void secp256k1_gej_double_nonzero(secp256k1_gej *r, const secp256k1_gej *a, secp25...
            ^
../src/secp256k1-src/src/group.h:103:13: warning: unused function 'secp256k1_gej_double_var'
      [-Wunused-function]
static void secp256k1_gej_double_var(secp256k1_gej *r, const secp256k1_gej *a, secp256k1_...
            ^
../src/secp256k1-src/src/group.h:106:13: warning: unused function 'secp256k1_gej_add_var'
      [-Wunused-function]
static void secp256k1_gej_add_var(secp256k1_gej *r, const secp256k1_gej *a, const secp256...
            ^
../src/secp256k1-src/src/group.h:109:13: warning: unused function 'secp256k1_gej_add_ge'
      [-Wunused-function]
static void secp256k1_gej_add_ge(secp256k1_gej *r, const secp256k1_gej *a, const secp256k...
            ^
../src/secp256k1-src/src/group.h:114:13: warning: unused function 'secp256k1_gej_add_ge_var'
      [-Wunused-function]
static void secp256k1_gej_add_ge_var(secp256k1_gej *r, const secp256k1_gej *a, const secp...
            ^
../src/secp256k1-src/src/group.h:117:13: warning: unused function 'secp256k1_gej_add_zinv_var'
      [-Wunused-function]
static void secp256k1_gej_add_zinv_var(secp256k1_gej *r, const secp256k1_gej *a, const se...
            ^
../src/secp256k1-src/src/group.h:125:13: warning: unused function 'secp256k1_gej_clear'
      [-Wunused-function]
static void secp256k1_gej_clear(secp256k1_gej *r);
            ^
../src/secp256k1-src/src/group.h:128:13: warning: unused function 'secp256k1_ge_clear'
      [-Wunused-function]
static void secp256k1_ge_clear(secp256k1_ge *r);
            ^
../src/secp256k1-src/src/group.h:131:13: warning: unused function 'secp256k1_ge_to_storage'
      [-Wunused-function]
static void secp256k1_ge_to_storage(secp256k1_ge_storage *r, const secp256k1_ge *a);
            ^
../src/secp256k1-src/src/group.h:134:13: warning: unused function 'secp256k1_ge_from_storage'
      [-Wunused-function]
static void secp256k1_ge_from_storage(secp256k1_ge *r, const secp256k1_ge_storage *a);
            ^
../src/secp256k1-src/src/group.h:137:13: warning: unused function 'secp256k1_ge_storage_cmov'
      [-Wunused-function]
static void secp256k1_ge_storage_cmov(secp256k1_ge_storage *r, const secp256k1_ge_storag...
            ^
../src/secp256k1-src/src/group.h:140:13: warning: unused function 'secp256k1_gej_rescale'
      [-Wunused-function]
static void secp256k1_gej_rescale(secp256k1_gej *r, const secp256k1_fe *b);
            ^
In file included from ../src/privatekey.cc:4:
In file included from ../src/secp256k1-src/src/scalar_impl.h:20:
../src/secp256k1-src/src/scalar_4x64_impl.h:83:12: warning: unused function
      'secp256k1_scalar_add' [-Wunused-function]
static int secp256k1_scalar_add(secp256k1_scalar *r, const secp256k1_scalar *a, const sec...
           ^
../src/secp256k1-src/src/scalar_4x64_impl.h:897:12: warning: unused function
      'secp256k1_scalar_shr_int' [-Wunused-function]
static int secp256k1_scalar_shr_int(secp256k1_scalar *r, int n) {
           ^
In file included from ../src/privatekey.cc:4:
../src/secp256k1-src/src/scalar_impl.h:225:13: warning: unused function
      'secp256k1_scalar_inverse_var' [-Wunused-function]
static void secp256k1_scalar_inverse_var(secp256k1_scalar *r, const secp256k1_scalar *x) {
            ^
In file included from ../src/privatekey.cc:4:
In file included from ../src/secp256k1-src/src/scalar_impl.h:20:
../src/secp256k1-src/src/scalar_4x64_impl.h:140:13: warning: unused function
      'secp256k1_scalar_negate' [-Wunused-function]
static void secp256k1_scalar_negate(secp256k1_scalar *r, const secp256k1_scalar *a) {
            ^
../src/secp256k1-src/src/scalar_4x64_impl.h:156:12: warning: unused function
      'secp256k1_scalar_is_high' [-Wunused-function]
static int secp256k1_scalar_is_high(const secp256k1_scalar *a) {
           ^
../src/secp256k1-src/src/scalar_4x64_impl.h:168:12: warning: unused function
      'secp256k1_scalar_cond_negate' [-Wunused-function]
static int secp256k1_scalar_cond_negate(secp256k1_scalar *r, int flag) {
           ^
63 warnings generated.
  CXX(target) Release/obj.target/secp256k1/src/publickey.o
  CXX(target) Release/obj.target/secp256k1/src/signature.o
  CXX(target) Release/obj.target/secp256k1/src/ecdsa.o
../src/ecdsa.cc:88:3: warning: ignoring return value of function declared with
      'warn_unused_result' attribute [-Wunused-result]
  obj->Set(info.GetIsolate()->GetCurrentContext(), Nan::New<v8::String>("signature").ToLocalChecked(), COPY_BUFFER(&output[0], 64));
  ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/ecdsa.cc:89:3: warning: ignoring return value of function declared with
      'warn_unused_result' attribute [-Wunused-result]
  obj->Set(info.GetIsolate()->GetCurrentContext(), Nan::New<v8::String>("recovery").ToLocalChecked(), Nan::New<v8::Number>(recid));
  ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
  CXX(target) Release/obj.target/secp256k1/src/ecdh.o
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/src/secp256k1.o
In file included from ../src/secp256k1-src/src/secp256k1.c:11:
../src/secp256k1-src/src/field_impl.h:266:13: warning: unused function 'secp256k1_fe_inv_all_var'
      [-Wunused-function]
static void secp256k1_fe_inv_all_var(secp256k1_fe *r, const secp256k1_fe *a, size_t len) {
            ^
In file included from ../src/secp256k1-src/src/secp256k1.c:13:
../src/secp256k1-src/src/group_impl.h:202:13: warning: unused function
      'secp256k1_ge_set_infinity' [-Wunused-function]
static void secp256k1_ge_set_infinity(secp256k1_ge *r) {
            ^
../src/secp256k1-src/src/group_impl.h:691:12: warning: unused function
      'secp256k1_gej_has_quad_y_var' [-Wunused-function]
static int secp256k1_gej_has_quad_y_var(const secp256k1_gej *a) {
           ^
../src/secp256k1-src/src/group_impl.h:272:12: warning: unused function
      'secp256k1_gej_is_valid_var' [-Wunused-function]
static int secp256k1_gej_is_valid_var(const secp256k1_gej *a) {
           ^
In file included from ../src/secp256k1-src/src/secp256k1.c:14:
../src/secp256k1-src/src/ecmult_impl.h:1135:12: warning: unused function
      'secp256k1_ecmult_multi_var' [-Wunused-function]
static int secp256k1_ecmult_multi_var(const secp256k1_ecmult_context *ctx, secp256k1_scra...
           ^
../src/secp256k1-src/src/ecmult_impl.h:669:12: warning: unused function
      'secp256k1_ecmult_strauss_batch_single' [-Wunused-function]
static int secp256k1_ecmult_strauss_batch_single(const secp256k1_ecmult_context *actx, se...
           ^
../src/secp256k1-src/src/ecmult_impl.h:1042:12: warning: unused function
      'secp256k1_ecmult_pippenger_batch_single' [-Wunused-function]
static int secp256k1_ecmult_pippenger_batch_single(const secp256k1_ecmult_context *actx, ...
           ^
7 warnings generated.
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/contrib/lax_der_parsing.o
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/contrib/lax_der_privatekey_parsing.o
  SOLINK_MODULE(target) Release/secp256k1.node
+ ganache-cli@6.7.0
added 88 packages from 85 contributors in 13.271s
:~ me$ ganache -cli
-bash: ganache: command not found
:~ me$ truffle
-bash: truffle: command not found

## Context
This is a continuation of the issue #674
Can not Install ganache cli on Mac OS Mojave (version 10.14.6) #674
The issue got resolved temporarily but when I tried to reuse ganache a few weeks later it was no longer working. I have no idea how to fix it as I can not figure out where is the problem coming from.

## Your Environment
* Ganache cli Version: ganache-cli@6.7.0
* Version of Truffle/Remix/Other tools used: truffle@5.0.41
* NodeJS Version: npm 6.12.0 & node.js 12.13.0
* Operating System and version: Mac OS Catalina (version 10.15)

**Comment by davidmurdoch** [comment]
This is likely an issue with your node/npm installation. Do any other globally installed modules work for you? If not, you'll need to figure out what that issue is. You could also try using the [yarn package manager](https://yarnpkg.com/lang/en/).

In the mean time you could use `npx ganache-cli` and `npx truffle`.

**Comment by BTT21000** [comment]
Hi @davidmurdoch 

Thank you for your answers.

See below my 3 comments:

**1. Other global npm modules**
I have completely uninstalled node and reinstalled from scratch the version 13.0
It seems like the location where the node modules are installed is strange, see below where are the folder globally saved:
:~ me$ node -v
v13.0.1
:~ me$ npm -v
6.12.0
:~ me$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Apple/bin:/usr/local/share/dotnet:~ /.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin
:~ me$ npm install -g ganache-cli
/Users/me/~ /.npm-global/bin/ganache-cli -> /Users/me/~ /.npm-global/lib/node_modules/ganache-cli/cli.js
+ ganache-cli@6.7.0
updated 1 package in 3.441s
:~ me$ npm install -g truffle
/Users/me/~ /.npm-global/bin/truffle -> /Users/me/~ /.npm-global/lib/node_modules/truffle/build/cli.bundled.js

> truffle@5.0.42 postinstall /Users/me/~ /.npm-global/lib/node_modules/truffle
> node ./scripts/postinstall.js

- Fetching solc version list from solc-bin. Attempt #1
+ truffle@5.0.42
added 27 packages from 439 contributors in 13.658s

:~ me$ ganache -cli
-bash: ganache: command not found

:~ me$ truffle
-bash: ganache: command not found

Note that I have tried to install another package globally to test and I get the same issue, the command can not run the program (see example of jshint below):

:~ me$ npm install -g jshint
/Users/me/~ /.npm-global/bin/jshint -> /Users/me/~ /.npm-global/lib/node_modules/jshint/bin/jshint
+ jshint@2.10.2
added 31 packages from 15 contributors in 2.135s
:~ me$ jshint
-bash: jshint: command not found

Why do these globally installed module can not be executed from the command line?

**2. Yarn**
I have installed yarn which seems to work fine.
However when I want to install and use ganache cli, it does not find the command again (see below):
Note that node has been installed via brew and the node shell works fine.

Could you please assist?

:~ me$ yarn global add ganache-cli
yarn global v1.19.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "ganache-cli@6.7.0" with binaries:
      - ganache-cli
✨  Done in 0.92s.
:~ me$ ganache -cli
-bash: ganache: command not found

**3. npx command for ganache-cli and truffle**

The npx command work well for ganache-cli and truffle

What are the limitations of using npx instead of a conventional installation?

Will I still be able to pursue a long term project with ganache-cli and truffle even if I'm using npx?
Or do I need to keep the same terminal windows open all the time? Would that be bad for my computer/CPU?

Thank you.

Best regards

**Comment by nicholasjpaterno** [comment]
Closing since you've solved the issue.  Please reopen if this is in error!

**Comment by Wiesel2000** [comment]
Hi There,
The issue has not been resolved yet.
Could you please address my last query before closing.
Thank you.

**Comment by BTT21000** [comment]
> Closing since you've solved the issue. Please reopen if this is in error!

Hello @nicholasjpaterno,
The issue has not been resolved yet.
Could you please address the latest queries (see my last post above) before.
Thank you.

**Comment by davidmurdoch** [comment]
@Wiesel2000 I'm not confident we'll be able to help you, as the issue seems to be with your local node/npm installation. Running npm commands via `sudo` likely had lots of unintended side effects.

**Comment by BTT21000** [comment]
Hi @davidmurdoch,
Thanks for your comment.
What should I do to restart everything from scratch for item 1 (npm approach)?
Could you please also comment about items 2 and 3 in my post above?
Thank you,
Best regards.

**Comment by BTT21000** [comment]
> @Wiesel2000 I'm not confident we'll be able to help you, as the issue seems to be with your local node/npm installation. Running npm commands via `sudo` likely had lots of unintended side effects.

Hi @davidmurdoch & @nicholasjpaterno ,

Following up on your comment above, does it mean that I no other choice than reset my laptop to factory settings (after having done a back up)?
Or is there another way to clean up the unintended side effects you mentioned?

**Comment by nicholasjpaterno** [comment]
@Wiesel2000 sorry for the late response, both @davidmurdoch and I haven't had a chance to review this.

Unfortunately, it seems that we won't be able to help with problems 1 and 2.  These are more general node.js issues that seem to have resulted during its installation.

For question 3, `npx` is a replacement for installing global packages since it can reach into the local node_modules to run package binaries. It encourages you to install packages locally, but still be able run them as if they were global.  Youre safe to close ganache and reopen with npx anytime!

I'm going to close this issue for now, but please reopen if you think this issue is still unresolved!

**Comment by BTT21000** [comment]
Hi @nicholasjpaterno  and @davidmurdoch,
Just to let you know that the problem finally got resolved with the precious help of the node.js.
If you're interested in the solution, here is the thread: https://github.com/nodejs/help/issues/2312
Best regards.

**Comment by nicholasjpaterno** [comment]
@Wiesel2000 Awesome!  Really glad to hear that you were able to resolve this!  Also, thanks for the link, this is greatly appreciated and will be useful for the next person who might run into this problem!

**Comment by nicholasjpaterno** [comment]
@Wiesel2000 I just read through the thread.  If you want this to run whenever you start a terminal, add this line `PATH=~/.npm-global/bin:$PATH` to the end of your `~/.bashrc` or `~/.bash_profile` or whatever the mac alternative would be!  Hope this helps!  All the best.

**Comment by liam-ot** [comment]
run 
`npm bin -g` 

if you get something like
`/usr/local/Cellar/node/16.0.0/bin
(not in PATH env variable)`

run
`export PATH=$PATH:/usr/local/Cellar/node/16.0.0/bin`

on zsh this _also_ works
`path+=(/usr/local/Cellar/node/16.0.0/bin)`
