### ISSUE TITLE
TypeError: unexpected type [object Object], use Uint8Array while running

### ISSUE THREAD

**Issue by Aldekein** [ConsenSys-archive/ganache-cli-archive#69]
I've upgraded to the latest version on OS X but it fails when I run `testrpc`:

``` /usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/eth-lightwallet/node_modules/tweetnacl/nacl-fast.js:2152
       throw new TypeError('unexpected type ' + t + ', use Uint8Array');
             ^
TypeError: unexpected type [object Object], use Uint8Array
    at checkArrayTypes (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/eth-lightwallet/node_modules/tweetnacl/nacl-fast.js:2152:14)
    at Object.nacl.secretbox (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/eth-lightwallet/node_modules/tweetnacl/nacl-fast.js:2201:3)
    at Function.KeyStore._encryptString (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/eth-lightwallet/lib/keystore.js:113:21)
    at new KeyStore (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/eth-lightwallet/lib/keystore.js:91:29)
    at new Blockchain (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/blockchain.js:45:19)
    at new Manager (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/manager.js:14:21)
    at Object.Server.provider (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/server.js:153:19)
    at Object.Server.server (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/server.js:23:25)
    at Object.TestRPC.server (/usr/local/lib/node_modules/ethereumjs-testrpc/index.js:23:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/ethereumjs-testrpc/bin/testrpc:42:22)
```

I have `ethereumjs-testrpc@2.0.3` and in install logs I see that it's using `eth-lightwallet@2.3.1 (scrypt-async@1.2.0, rlp@2.0.0, tweetnacl@0.13.2, bignumber.js@2.0.7, crypto-js@3.1.6, elliptic@3.1.0, bitcore-mnemonic@1.0.1, bitcore-lib@0.13.14)`. The latest tweetnacl version is 0.14.3 but probably the old version is cached somewhere in dependencies. 

I'm not deep in nodejs so I don't understand how to fix it :(

**Comment by tcoulter** [comment]
Can you upgrade your version of NodeJS to 5.x? That's likely the issue.

**Comment by Aldekein** [comment]
@tcoulter thank you, I've updated node, npm and all of the packages and it fixed the problem.
