### ISSUE TITLE
Starting ganache with hardfork set to istanbul results in Hardfork with name instanbul not supported error

### ISSUE THREAD

**Issue by BogdanHabic** [ConsenSys-archive/ganache-cli-archive#730]
* Link to my question on twitter: [Twitter link](https://twitter.com/BogdanHabic/status/1252596733890236418)

## Expected Behavior

Starting `ganache-cli` with `--hardfork` set to `istanbul` should run the CLI with the instabul hardfork enabled.

## Current Behavior

Starting `ganache-cli` with `--hardfork` set to `istanbul` triggers an error:
```
Error: Hardfork with name instanbul not supported
```

## Steps to Reproduce (for bugs)

```bash
yarn global remove ganache-cli
yarn global add ganache-cli
ganache-cli --hardfork instanbul
Ganache CLI v6.9.1 (ganache-core: 2.10.2)
Error: Hardfork with name instanbul not supported
    at e.setHardfork (/Users/bogdanhabic/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:79312)
    at new e (/Users/bogdanhabic/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:78313)
    at Function.e.forCustomChain (/Users/bogdanhabic/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:78404)
    at A.createVMFromStateTrie (/Users/bogdanhabic/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:17:116091)
    at /Users/bogdanhabic/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:17:115641
    at /Users/bogdanhabic/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:17:116884
    at /Users/bogdanhabic/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:53:1368709
    at /Users/bogdanhabic/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:53:1367762
    at /Users/bogdanhabic/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:53:1372648
    at /Users/bogdanhabic/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:53:1369997
    at /Users/bogdanhabic/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:24:80836
    at /Users/bogdanhabic/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:53:1394962
    at ReadFileContext.c.readFile [as callback] (/Users/bogdanhabic/.config/yarn/global/node_modules/ganache-cli/build/ganache-core.node.cli.js:53:1379094)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13)
```

## Context

We have users reporting gas mismatch errors when using [the Tenderly CLI export feature](https://github.com/Tenderly/tenderly-cli#export). This happens when the hardfork isn't the one reported by Ganache.

## Your Environment
* Version used: Ganache CLI v6.9.1 (ganache-core: 2.10.2)
* Version of Truffle/Remix/Other tools used:
* NodeJS Version: v10.13.0
* Operating System and version (include distro if Linux): macOS 10.14.6
* Link to your project or repro gist: N/A

**Comment by nicholasjpaterno** [comment]
@BogdanHabic looks you're misspelling istanbul.  Try `ganache-cli --hardfork istanbul`.  Please reopen if this doesn't solve the problem!

**Comment by BogdanHabic** [comment]
🤦‍♂️, yup, you're correct. It's working as expected when typed in correctly 😅
