### ISSUE TITLE
`Cannot read property 'split' of undefined` when trying to compile

### ISSUE THREAD

**Issue by redsquirrel** [ConsenSys-archive/ganache-cli-archive#79]
I have `testrpc` running and I'm attempting to compile a contract using web3.

```
var Web3 = require('web3');
var web3 = new Web3();
web3.setProvider(new web3.providers.HttpProvider('http://0.0.0.0:8545'));
web3.eth.compile.solidity('contract foo {}');
```

This results in the following error:

```
Error: TypeError: Cannot read property 'split' of undefined
    at Compiler.compile_solidity (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/compiler.js:14:34)
    at Manager.eth_compileSolidity (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/manager.js:197:23)
    at Manager.handleRequest (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/manager.js:75:10)
    at next (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:93:18)
    at VmSubprovider.handleRequest (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/vm.js:42:12)
    at next (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:93:18)
    at GethDefaults.handleRequest (/usr/local/lib/node_modules/ethereumjs-testrpc/lib/gethdefaults.js:17:12)
    at next (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:93:18)
    at FilterSubprovider.handleRequest (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/filters.js:76:7)
    at next (/usr/local/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:93:18)
    at Object.module.exports.InvalidResponse (/Users/davehoover/Projects/node_modules/web3/lib/web3/errors.js:35:16)
    at RequestManager.send (/Users/davehoover/Projects/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Object.send [as solidity] (/Users/davehoover/Projects/node_modules/web3/lib/web3/method.js:145:58)
    at Object.<anonymous> (/Users/davehoover/Projects/live-libs/foo.js:4:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
```

This error appears to be happening because the `exec()` call to `solc` is returning no output.

Here's what `solc --version` returns from the command line:

```
solc, the solidity compiler commandline interface
Version: 0.3.2-81ae2a78/RelWithDebInfo-Darwin/appleclang/Interpreter
```

**Comment by redsquirrel** [comment]
Follow up: I believe this is still not working in testrpc.

That said, it seems like compiling via web3 is an non-standard approach. I worked around this issue by using a more standard compilation approach: use [solc-js](https://github.com/ethereum/solc-js).

**Comment by tcoulter** [comment]
Ya, it probably isn't working. I haven't updated that code since it was migrated from Ethersim - and I'm not sure it even worked then. Most people aren't compiling with `eth_compileSolidity` because it seems like an unneeded step: as you mentioned, just call the compiler directly (or solc-js when using Javascript). If someone would like to fix compiling that'd be much appreciated.

**Comment by axic** [comment]
Quick note: I've added a solc subprovider (which uses solc-js) to provider-engine a while ago. That was working when I added it, perhaps it still is. It could replace the above code.

**Comment by tcoulter** [comment]
Excellent

On Thu, May 26, 2016 at 10:24 AM, Alex Beregszaszi <notifications@github.com

**Comment by tcoulter** [comment]
Fixed here, using the solc subprovider. Thanks @axic! https://github.com/ethereumjs/testrpc/commit/1a0c537fb9534dc637ec60f862241914029d5e8d
