### ISSUE TITLE
RPC method eth_getTransactionByBlockNumberAndIndex not supported

### ISSUE THREAD

**Issue by kumavis** [ConsenSys-archive/ganache-cli-archive#95]
```
╭─kumavis@xyzs-MacBook-Pro  ~/dev/vm-fail ‹node-v4.2.3›  
╰─$ curl -X POST -d '{"method": "eth_getTransactionByBlockNumberAndIndex", "params": ["0x01", "0x0"]}' localhost:8545 | jsonogram
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1677    0  1597  100    80   199k  10257 --:--:-- --:--:-- --:--:--  222k
└─ error
   ├─ message: Error: RPC method eth_getTransactionByBlockNumberAndIndex not supported.
    at Manager.handleRequest (/Users/kumavis/.nvm/versions/node/v4.2.3/lib/node_modules/ethereumjs-testrpc/lib/manager.js:63:16)
    at next (/Users/kumavis/.nvm/versions/node/v4.2.3/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:93:18)
    at VmSubprovider.handleRequest (/Users/kumavis/.nvm/versions/node/v4.2.3/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/vm.js:42:12)
    at next (/Users/kumavis/.nvm/versions/node/v4.2.3/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:93:18)
    at GethDefaults.handleRequest (/Users/kumavis/.nvm/versions/node/v4.2.3/lib/node_modules/ethereumjs-testrpc/lib/gethdefaults.js:17:12)
    at next (/Users/kumavis/.nvm/versions/node/v4.2.3/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:93:18)
    at FilterSubprovider.handleRequest (/Users/kumavis/.nvm/versions/node/v4.2.3/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/filters.js:76:7)
    at next (/Users/kumavis/.nvm/versions/node/v4.2.3/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:93:18)
    at ReactiveBlockTracker.handleRequest (/Users/kumavis/.nvm/versions/node/v4.2.3/lib/node_modules/ethereumjs-testrpc/lib/reactiveblocktracker.js:27:12)
    at next (/Users/kumavis/.nvm/versions/node/v4.2.3/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:93:18)
   └─ code: -32000
```

**Comment by tcoulter** [comment]
Yo, @kumavis. Is this an important feature to you?

**Comment by kumavis** [comment]
rpc compliance is important to me 🎱

**Comment by tcoulter** [comment]
Rate this specific feature given your current needs.

**Comment by tcoulter** [comment]
Fixed on the `develop` branch, with tests. Closing.
